### ISSUE TITLE
extend tar_script() argument library_targets  

### ISSUE THREAD

**Issue by mkoohafkan** [ropensci/targets#1035]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

**BLUF**: Extend `library_targets` to instead take a character vector of package names and add `library()` calls for each entry. Default value would be `library_targets = "targets"` which would be equivalent to current behavior `library_targets = TRUE`.

I am using `tar_script()` in a package to build pipelines from a template and `substitute` in user arguments (usually a path to an external file or some other initialization arguments). However, any usage of `library()` or `require()` in the template script produces warnings in R CMD CHECK.

Current solutions: 
- use `requireNamespace()` and explicitly reference package names in the template script, e.g., `pkname::function()`
- Use a placeholder function (.e.g, `libcall`) and then use `substitute(tar_script({...}), env = list(libcall = quote(library)))`

**Comment by wlandau** [comment]
The second workaround sounds like a good fit for your package development scenario, and you may even be able to simplify it using `rlang::call2()`. The feature you propose is an edge case with a straightforward workaround, so I would prefer not to build it directly into `targets`.
