### ISSUE TITLE
Allow `targets::tar_source` to `chdir` change directory to the source file

### ISSUE THREAD

**Issue by dipterix** [ropensci/targets#1040]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Allow `source` to change directory when sourcing external scripts. Default to `FALSE` to be compatible (have exactly the same behavior) with current implementation.

```r
targets::tar_source <- function (files = "R", chdir = FALSE, envir = targets::tar_option_get("envir")) 
{
    ...
    lapply(r_scripts, function(file) {
        # eval(parse(text = readLines(file, warn = FALSE)), envir = envir)
		source(file, local = envir, chdir = chdir, keep.source = FALSE)
        invisible()
    })
    invisible()
}
```

Alternatively `sys.source` could replace `source`

**Comment by dipterix** [comment]
The use case is the source file contains some small "data" or C scripts that are written by someone else assuming the workdir is the source file base path. This suggestion does not change the default behavior and is totally backward compatible

**Comment by wlandau** [comment]
Yeah, I think this extra bit of convenience is consistent with the intent of `tar_source()`. Added in 798db9befeb7152dac75db07602c6a4801a2929c.

**Comment by dipterix** [comment]
Thanks!
