### ISSUE TITLE
Targets using custom storage format appear outdated after upgrade from targets 0.14.3 to 1.0.0

### ISSUE THREAD

**Issue by mglev1n** [ropensci/targets#1064]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Issue

After upgrading from version 0.14.3 to the recently release 1.0.0 package on CRAN, I have noticed that targets using custom storage formats now appear "outdated". This issue is resolved when reverting back to 0.14.3 using `devtools::install_version("targets", version = "0.14.3")`. 

An example of a pipeline causing this problem is below - if the pipeline is run using targets 0.14.3, it becomes outdated after upgrading to targets 1.0.0. If targets is reverted to 0.14.3 (without re-running the pipeline), the targets again appear "Up to date":

```
# Writes a user-defined target script:
tar_script(
  {
    format_arrow_table <- function() {
      targets::tar_format(
        read = function(path) {
          arrow::read_parquet(path, as_data_frame = FALSE)
        },
        write = function(object, path) {
          arrow::write_parquet(object, path)
        },
        marshal = function(object) as.data.frame(object),
        unmarshal = function(object) arrow::Table$create(object)
      )
    }

    tar_option_set()
    list(tar_target(x, mtcars, format = format_arrow_table()))
  },
  ask = FALSE
)

writeLines(readLines("_targets.R"))
```

The custom file format `format_arrow_table()` is adapted from the https://github.com/ropensci/targets/discussions/805#discussion-3935595 discussion in the `tarchetypes` repository, but since the issue seems related to the new targets version I posted here. I don't use any other "custom" file formats, so I'm not sure whether these may be affected. I've tested `format = "qs"`, and this does not appear to have the same issue.

**Comment by wlandau** [comment]
Sorry about the frustration that may have caused. I needed to add a `copy` argument to `tar_format()` to address https://github.com/ropensci/targets/discussions/1041 via https://github.com/ropensci/targets/pull/1042, and I could not avoid invalidating those targets. I hope to keep the formats the way they are from now on and avoid issues like this one. You can upgrade to 1.0.0 and still keep your targets up to date if you set `tar_option_set(cue = tar_cue(format = FALSE))`.
