### ISSUE TITLE
[Bug] Heterogeneous {crew} workers invalid class

### ISSUE THREAD

**Issue by mglev1n** [ropensci/targets#1065]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Issue
When following the "Heterogenous Workers" example in the {targets} manual (https://books.ropensci.org/targets/crew.html#heterogeneous-workers), the following error appears: 

```
Last error: controller for tar_make() must be a valid object of class "crew_class_controller" from the {crew} R package.
```

This seems to be a result of the `validate_crew_controller()` function. Should this function also accept `crew_class_controller_group` as a valid class? https://github.com/ropensci/targets/blob/384da1bbf3bc953987ec1668d1df27a29f3a5c13/R/class_crew.R#L243-L254

**Comment by wlandau** [comment]
Yes it is supposed to work with controller groups, thanks for letting me know. Should be fixed now.
