### ISSUE TITLE
Mysterious "'errorValue' int 5 | Timed out" with crew and covr

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#1076]
The `crew` tests in `targets` are working fine in `R CMD check`, but now they always fail in `covr::package_coverage()` with `"'errorValue' int 5 | Timed out"` resulting from a call to `mirai::daemons()`. The smallest reproducible example I can generate is to replace `tests/testthat.R` in the source code of `targets` with the R code below.

```r
controller <- crew::crew_controller_local(seconds_interval = 0.5)
controller$start()
controller$push(
  command = targets:::target_run(
    targets::tar_target_raw("x", quote(1L)),
    globalenv(),
    "_targets"
  )
)
controller$wait()
controller$pop()
controller$terminate()
```

Then, run `covr::package_coverage()` on `targets`.

Remarks:

* I cannot reproduce this example with just `mirai` or even just `crew`.
* If I remove the `targets::tar_run()` command and replace with something that does not use `targets`, then the coverage workflow runs without error.

FYI @shikokuchuo, just in case anything obvious occurs to you. Since R CMD check is running fine, I don't think I will worry about this one too much. (E.g. it won't hold up the next CRAN release.)

**Comment by shikokuchuo** [comment]
I used your example to replace the tests in `targets` and have no trouble running it locally using the latest build (0% coverage) but with decent positive coverage if I replace the tests in `crew` and `mirai` respectively. Works using both `covr::package_coverage()` and `covr::report()`.

From the error message it seems to suggest that it is pulling the CRAN versions of nanonext/mirai rather than the latest.

**Comment by wlandau** [comment]
Thanks for checking on your end. When I run it, I see:

```r
> controller <- crew::crew_controller_local(seconds_interval = 0.5)
> controller$start()
> controller$push(
+   command = targets:::target_run(
+     targets::tar_target_raw("x", quote(1L)),
+     globalenv(),
+     "_targets"
+   )
+ )
> controller$wait()
Error:
! invalid daemons: structure(5L, class = "errorValue")
```

You're right, it must be something to do with my local package library. It seems to be passing on GitHub Actions, which is all I need `covr` for anyway.

**Comment by wlandau** [comment]
I can no longer reproduce the problem locally after upgrading to `nanonext` 0.8.3.9007. Looking back at recent test coverage successes and failures on GitHub Actions, I see all the failures used `nanonext` <= 0.8.3.9005 and all the successes used `nanonext` >= 0.8.3.9006. So although I do not understand what cause the original issue, I am fine to consider it solved. (Even `covr`'s documentation admits there are strange and mysterious edge cases because of how it instruments code.)

**Comment by shikokuchuo** [comment]
I see the failures you're getting. Let me take a quick look into this.

**Comment by wlandau** [comment]
`mirai` 0.8.7.9015 seems to have worked, thanks @shikokuchuo!
