### ISSUE TITLE
partial reading from tabular data storage

### ISSUE THREAD

**Issue by Sage0614** [ropensci/targets#1080]
## Proposal

I wonder if it is possible to expose partial reading from a tabular storage format, like fst or parquet, to only read a subset of cols/rows of the data? currently I don't see a way to do this in tar_load() or tar_read() directly.

**Comment by wlandau** [comment]
I do not have plans to build in a feature like this, but if you know which row subset you will want in advance, you can create a downstream target that returns the subset.
