### ISSUE TITLE
Option to turn off or configure pipeline-level error messages

### ISSUE THREAD

**Issue by dipterix** [ropensci/targets#1081]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

I wrote customizable functions and shiny apps to dynamically generate the pipelines so users don't need to code (nor they know how to code). Sometimes the pipelines are errored loudly on purpose (like users enter something wrong or I need them to call my numbers). But my clients thought they need to go to targets website to debug something instead. The hard-coded error messages can sometimes cause confusion. And it would be great if we could change that globally via `options`, or locally when `tar_make` is executed.

Currently `utils_callr.R` hard-code the error message with links to target website. The messages are for the code pipeline developers ( dev mode ), not quite fit for the end-users (production mode). 

```r
callr_error <- function(condition, fun) {
  message <- sprintf(
    paste0(
      "Error running targets::%s()\n",
      "  Error messages: ",
      "targets::tar_meta(fields = error, complete_only = TRUE)\n",
      "  Debugging guide: https://books.ropensci.org/targets/debugging.html\n",
      "  How to ask for help: https://books.ropensci.org/targets/help.html\n",
      "  Last error: %s"
    ),
    fun,
    conditionMessage(condition)
  )
  tar_throw_run(message, class = class(condition))
}
```

**Comment by wlandau** [comment]
As of #997, you actually do have the original classes of the user-side errors as well. And to get the original error messages, you could either regex the output of `conditionMessage(condition)` in the `tryCatch()` handler, or you could get the stored error messages from `tar_meta()$error`.

**Comment by dipterix** [comment]
> As of #997, you actually do have the original classes of the user-side errors as well. 

I see, so that means if I want to capture both expected and unexpected errors, I am expected to try-catch on each targets respectively

Something like

```r
tar_target(name, {
  tryCatch({...}, error = function(e) {
    class(e) <- c(paste0("targets_callr_error:", paste(e$message, collapse = "\n")), class(e))
    stop(e)
  })
})
```

> And to get the original error messages, you could either regex the output of `conditionMessage(condition)` in the `tryCatch()` handler, or you could get the stored error messages from `tar_meta()$error`.

So in `tar_make`, I can

```r

tryCatch(tar_make(), tar_condition_run = \(cond) {
  cls <- class(cond)
  cls <- cls[grepl("^targets_callr_error", cls)]
  if(length(cls) >= 1){
    cls <- cls[[1]]
    stop(cls)
  } else {
    stop(cond)
  }
}

```

But this feels like a hack... since I'm passing the error messages via error class...

**Comment by dipterix** [comment]
> Which cases come up for you? Sorry, but I am having trouble understanding what is missed in my original tryCatch() suggestion.

Functions like `url_process_error`, `stem_tar_assert_nonempty`, `builder_error_exit`, ... also call `tar_throw_run`. If I catch `tar_throw_run` directly, I am expected to handle all error messages raised by these functions. If I want to handle these error individually, I have to regexp these error messages in the same condition handlers. Ideally I wish catching errors be layered: if someone just want to capture the url errors, they write handlers for the url errors. If they want to handle callr errors, then they just need to write handlers for callr errors.

> I think it would be straightforward to add a special error class in [callr_error() here](https://github.com/ropensci/targets/blob/aa09d6798669d663e7d42c330bec475648e6049f/R/utils_callr.R#L45)

I like this idea: it allows devs to handle different errors respectively, also it does not affect existing code unless someone accidentally occupies the new error class.

```r
tryCatch(
  tar_make(), 
  tar_condition_run_callr_error = \(condition) stop("This is callr error message"),
  tar_condition_run_url_error = \(condition) stop("This is url error message"),
  tar_condition_run = \(condition) stop("your message2")
)
```

**Comment by wlandau** [comment]
> url_process_error, stem_tar_assert_nonempty, builder_error_exit, ... also call tar_throw_run.

Do you need to distinguish among all these kinds of errors? Ultimately, they all get caught and forwarded to [`callr_error()`](https://github.com/ropensci/targets/blob/aa09d6798669d663e7d42c330bec475648e6049f/R/utils_callr.R#L45) anyway. So if I add a special pipeline error class in `callr_error()`, they would all have this class.

One alternative I may not have spelled out is the use of `tar_meta()`. This will return the saved error messages from all targets that have them. You can use `tar_errored()` to get only the most recently errored targets.

```r
tryCatch(
  tar_make(),
  tar_condition_run = \(condition) {
    meta <- tar_meta(names = any_of(tar_errored()), fields = any_of("error"))
    stop(paste("errored targets:", paste0(meta$name, ": ", meta$error), collapse = "\n"))
  }
)
```

**Comment by dipterix** [comment]
Great, this is nice. Thanks!

**Comment by wlandau** [comment]
I wonder why you are seeing (1). `tar_errored()` just pulls from `_targets/meta/progress` which gets reset every run and does not include previous runs. Could something else be responsible? It works on my end.

``` r
library(targets)

# Run all targets so all the error messages are stored.
tar_script({
  library(targets)
  library(tarchetypes)
  tar_option_set(error = "continue")
  tar_plan(
    a = stop(c),
    b = stop(d),
    c = "error c",
    d = "error d"
  )
})
tar_make()
#> ▶ start target c
#> ● built target c [0.001 seconds]
#> ▶ start target d
#> ● built target d [0 seconds]
#> ▶ start target a
#> Error: error c
#> 
#> ✖ error target a
#> ▶ start target b
#> Error: error d
#> 
#> ✖ error target b
#> ▶ end pipeline [0.067 seconds]
#> Warning message:
#> 2 targets produced errors. Run targets::tar_meta(fields = error, complete_only = TRUE) for the messages.

# Check that all targets have error messages.
tar_meta(fields = any_of("error"), complete_only = TRUE)
#> # A tibble: 2 × 2
#>   name  error  
#>   <chr> <chr>  
#> 1 a     error c
#> 2 b     error d

# Stop on error
tar_script({
  library(targets)
  library(tarchetypes)
  tar_plan(
    a = stop(c),
    b = stop(d),
    c = "error c",
    d = "error d"
  )
})

# Catch just the error message of target b.
tryCatch(
  tar_make(names = any_of("b")),
  error = function(condition) {
    meta <- tar_meta(names = any_of(tar_errored()), fields = any_of("error"))
    stop(
      paste(
        "errored targets:\n",
        paste0(meta$name, ": ", meta$error),
        collapse = "\n"
      ),
      call. = FALSE
    )
  }
)
#> ✔ skip target d
#> ▶ start target b
#> ✖ error target b
#> ▶ end pipeline [0.052 seconds]
#> Error: errored targets:
#>  b: error d
```

<sup>Created on 2023-06-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.0 (2023-04-21)
#>  os       macOS Ventura 13.4
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Indiana/Indianapolis
#>  date     2023-06-22
#>  pandoc   3.1.2 @ /usr/local/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  backports     1.4.1      2021-12-13 [1] CRAN (R 4.3.0)
#>  base64url     1.4        2018-05-14 [1] CRAN (R 4.3.0)
#>  callr         3.7.3      2022-11-02 [1] CRAN (R 4.3.0)
#>  cli           3.6.1      2023-03-23 [1] CRAN (R 4.3.0)
#>  codetools     0.2-19     2023-02-01 [1] CRAN (R 4.3.0)
#>  data.table    1.14.8     2023-02-17 [1] CRAN (R 4.3.0)
#>  digest        0.6.31     2022-12-11 [1] CRAN (R 4.3.0)
#>  evaluate      0.21       2023-05-05 [1] CRAN (R 4.3.0)
#>  fansi         1.0.4      2023-01-22 [1] CRAN (R 4.3.0)
#>  fastmap       1.1.1      2023-02-24 [1] CRAN (R 4.3.0)
#>  fs            1.6.2      2023-04-25 [1] CRAN (R 4.3.0)
#>  glue          1.6.2      2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools     0.5.5      2023-03-23 [1] CRAN (R 4.3.0)
#>  igraph        1.4.2      2023-04-07 [1] CRAN (R 4.3.0)
#>  knitr         1.42       2023-01-25 [1] CRAN (R 4.3.0)
#>  lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.3.0)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
#>  pillar        1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
#>  processx      3.8.1      2023-04-18 [1] CRAN (R 4.3.0)
#>  ps            1.7.5      2023-04-18 [1] CRAN (R 4.3.0)
#>  purrr         1.0.1      2023-01-10 [1] CRAN (R 4.3.0)
#>  R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo          1.25.0     2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils       2.12.2     2022-11-11 [1] CRAN (R 4.3.0)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
#>  reprex        2.0.2      2022-08-17 [1] CRAN (R 4.3.0)
#>  rlang         1.1.1      2023-04-28 [1] CRAN (R 4.3.0)
#>  rmarkdown     2.21       2023-03-26 [1] CRAN (R 4.3.0)
#>  rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.3.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
#>  styler        1.10.1     2023-06-05 [1] CRAN (R 4.3.0)
#>  targets     * 1.1.3.9000 2023-06-21 [1] local
#>  tibble        3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
#>  tidyselect    1.2.0      2022-10-10 [1] CRAN (R 4.3.0)
#>  utf8          1.2.3      2023-01-31 [1] CRAN (R 4.3.0)
#>  vctrs         0.6.2      2023-04-19 [1] CRAN (R 4.3.0)
#>  withr         2.5.0      2022-03-03 [1] CRAN (R 4.3.0)
#>  xfun          0.39       2023-04-20 [1] CRAN (R 4.3.0)
#>  yaml          2.3.7      2023-01-23 [1] CRAN (R 4.3.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by wlandau** [comment]
For (2), you could try including `options(cli.unicode = FALSE)` in `_targets.R`. Otherwise, if `callr::r(func = function() message("cli"), show = TRUE)` reproduces the problem, then I would suggest troubleshooting the issue through `callr` and/or `cli` directly.

**Comment by dipterix** [comment]
Hi @wlandau my pipeline contains the following error:

```
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: The following issues found when validating subject ‘DemoSubject’ in project ‘test’.
1 - Electrode file missing
    008 (electrode 1-12,17-23,25-30)
```

The last line of error messsage was `008 (electrode 1-12,17-23,25-30)`.

However, when I was trying to capture `tar_condition_run` using:

```r
meta <- targets::tar_meta(names = targets::any_of(targets::tar_errored()),
                                    fields = targets::any_of("error"),
                                    complete_only = TRUE)
meta$error
#> [1] "The following issues found when validating subject DemoSubject in project test.1  Electrode file missing    008 electrode 112,1723,2530"
```

The `\n`, `(`, `-` are eaten by `targets`

**Comment by wlandau** [comment]
> The \n, (, - are eaten by targets.

{targets} cleans out these characters because they cannot be safely stored in the metadata text file and it would be too much overhead to base64 encode every message.

**Comment by dipterix** [comment]
The Base64 encoding encodes binary data into characters in a 64 bit alphabet. That entails a size increase of 33.3%; i.e. 3 bytes becomes 4 characters. I guess you mean runtime overhead?

**Comment by dipterix** [comment]
Hi @wlandau I'm using `tar_condition_run` to capture error conditions only, but instead I capture warnings as well...

After checking your code, I found `tar_message_run`, `tar_throw_run`, `tar_warn_run` all signal `tar_condition_run`.

Is there any way to distinguish these signals?

**Comment by wlandau** [comment]
Unfortunately, `callr` does not forward warnings to the main R process, so the same kind of exception handling via `tryCatch()` does not seem to be possible. But you could check `tar_meta(names = any_of(c(tar_errored(), tar_built())), fields = any_of("warnings"))` anyway, similarly to before.
