### ISSUE TITLE
Allow more customisation of defaults for `tar_*` functions

### ISSUE THREAD

**Issue by Moohan** [ropensci/targets#1085]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal
My specific use case is that I use `tar_visnetwork(level_separation = 750L, label = c("time", "size"))` quite regularly. It would be great if I could set the default `level_separation` and `label` somewhere, either in `tar_option_set` or in `_targets.yaml` using `tar_config_set`.

I think generally this is applicable to a lot of functions and there parameters where it would be good to have the ability to set default options for them.

**Comment by wlandau** [comment]
I added `tar_config_set()` configurable defaults for `label` and `level_separation`. Hopefully that helps.

There are so many arguments that I prefer to handle this sort of thing on a case-by-case basis.
