### ISSUE TITLE
Change size of the widget from tar_visnetwork

### ISSUE THREAD

**Issue by SanD94** [ropensci/targets#1091]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Here is the story: I would like to say first thank you for maintaining the useful library that saved lots of my time. Since I am a bit dumb person who does not remember the name of targets I generate, I mostly use tar_visnetwork() to check my target variables. To save a little bit of time in my workflow, I've also decided to integrate Jupyter Lab with R. Right now, it seems like because of the default size (960px x 500px coming from htmlwidgets) values, I cannot get a good look from tar_visnetwork(). If it's possible to add some parameters to tar_visnetwork() to change the size of the widget, I am much appreciated.

Here is the proposed parameter list: 

```r
tar_visnetwork <- function(
...,
height = NULL,
width = NULL
)
```

Note: If there's any convention that you follow, I am also happy to help you with the implementation.

Thanks!

**Comment by wlandau** [comment]
I have no plans to build in width/height directly into the` visNetwork` graphs, but you can supply these arguments to `visNetwork::visSize()` directly:

```r
library(magrittr)
library(targets)
library(visNetwork)
tar_visnetwork() %>%
  visOptions(width = "250px", height = "250px")
```

**Comment by SanD94** [comment]
I used that function before but it doesn't change the widget size itself, rather changes the vis-network within widget.

Thanks anyway!

**Comment by wlandau** [comment]
I'm not sure `targets` or `visNetwork` would be able to control the dimensions outside the widget. Maybe something in `htmlwidgets` or Jupyter?

**Comment by SanD94** [comment]
I traced the code back to `htmlwidgets`. What I can understand is that `visNetwork` let `htmlwidgets` use default values from `sizingPolicy`. When creating a widget from `visNetwork`, you can provide different sizes but changing those sizes after creating it is a little bit tricky, which leads to `visOptions` not working well for height and width.

I'll try to find a way and let you know about that. Maybe I should create an issue in `visNetwork`.
