### ISSUE TITLE
Attempt failed jobs N times (retries)

### ISSUE THREAD

**Issue by stemangiola** [ropensci/targets#1093]
## Prework

* [ x ] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [ x ] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Workflow managers such as makeflow retry failed jobs N times. This is practically useful because some failures are non-deterministic. 

For example, now I am getting one error because `scheduled cores 3, 5, 9 did not deliver results`, however sometimes this works, for reason that is not worth me investigating.

I think this is a practically very useful feature.

**Comment by wlandau** [comment]
You can implement retries for a target with the {retry} package. Outer hooks in {tarchetypes} could help apply retries to multiple targets.

**Comment by stemangiola** [comment]
Thanks,

I assume somethign like

```
tar_target(	se_normalised,  retry(normalise(se_filtered)))
```

**Comment by wlandau** [comment]
exaclty
