### ISSUE TITLE
Add a new target format `s4`

### ISSUE THREAD

**Issue by grantn5** [ropensci/targets#1096]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal
Some R packages work using s4 objects with multiple elements within them. A standard example of this would be the `Seurat` package for analysing single-cell RNA seq data. 

A standard workflow would look like;

```
library(dplyr)
library(Seurat)
library(patchwork)

# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

##Subset based on QC metrics
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

##Normalise 
pbmc <- NormalizeData(pbmc)

##find variable features
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
```

As the `pbmc` is an s4 class all operations are performed on the object and new elements are added. 

Currently, to my knowledge, this type of analysis is not possible in targets as each target has to have a unique name, if each time i performed an action on `pbmc` I saved it as a new target I would end up with a lot of redundancy in my saved targets in `_targets/objects` as I am saving the same s4 object each time with only one new element added. 

Would it be possible to add an additional option to the `format` argument of `tar_target()` for s4 objects to allow the same target to be manipulated and avoid excess storage of intermediate files in `_targets/objects`?

**Comment by wlandau** [comment]
Immutability is a core assumption in `targets`, we need it to be able to check if the tasks in the pipeline are up to date. In your situation, I would recommend grouping the same amount of work into fewer targets, e.g. subset and normalize in the same target. My general recommendation is at https://books.ropensci.org/targets/targets.html#how-much-a-target-should-do.
