### ISSUE TITLE
Option to select either tempdir() or tools::R_user_dir() for temporary cloud download files

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#1106]
Related: #1102, #1103. FYI @jds485.

Some enterprise cloud systems have really inefficient home directories and really fast temp directories, so I think we want to let the user choose where cloud staging/download files go. We should also default to `tempdir()`.

https://github.com/ropensci/targets/commit/c999968e182d232f517c0a9eb5bd24c75b197cdd should prevent a relapse of #1102.

**Comment by wlandau** [comment]
On second thought, let's just do `tempdir()` for network scratch. Reasons:

* File download is a lot slower than file copy, so it shouldn't matter for speed.
* Most systems have the same mount for tmpdir() and home.
* The only other systems I can think of are big corporate enterprise systems where hitting the network file system a lot is a bad idea anyway, so it's better in that case to download to tempdir() and then copy over when done.

**Comment by yihui** [comment]
Also an extra reason: `tools::R_user_dir()` [was introduced in R 4.0.0](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html), and using it indicates a dependency on `R >= 4.0.0`.
