### ISSUE TITLE
allow tar_script to append to file for dynamic pipeline building

### ISSUE THREAD

**Issue by stemangiola** [ropensci/targets#1114]
## Prework

* [ x ] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [ x ] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

I would like to build a high-level interface for allowing a user to build a pipeline, similar to what I did with tidyHeatmap, in which user-facing grammar is used to store commands that get realised when the object is evaluated. 

In order to do that, I need to append pipeline blocks to the same file. It would be nice to add

`tar_script(..., append = TRUE)`

Thanks.

**Comment by wlandau** [comment]
Your interface sounds like a neat idea.

The intent of `tar_script()` is to write an entire file, and it is rare to need to programmatically append lines post-hoc, so I think its makes more sense for your interface to handle that part directly. Functions `deparse()` and `substitute()` are helpful for quoting user input code and turning it into text to append.

**Comment by stemangiola** [comment]
A question on the same note: Can you call external variables, such as

```r
a = 10

tar_script({

list(
   tar_target(my, a)
)

})
```

**Comment by wlandau** [comment]
Only if you put the 'a' object inside the script.
