### ISSUE TITLE
Dynamic `tar_resources`, `tar_resources_crew`

### ISSUE THREAD

**Issue by stemangiola** [ropensci/targets#1128]
## Prework

* [ x ] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [ x ] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

For performant pipelines, I used to assign resources depending on the input size. For the same task (processing a dataset), I can have widely diverse inputs in terms of size (100Mb to 10Gb).

If my target input is a data frame and I use iteration = "group", I would like to 

 pass a column name as `resources =` so I can choose for every row if I have the resource 

- `slurm_mini`, 
- `slurm_small`, 
- `slurm_big`

```r
tar_target(
	pseudobulk_df_tissue_merged,
	pseudobulk_df_tissue |> aggregate() |> map_quantile_scale_abundance() |>  se_add_dispersion(),
	pattern = map(pseudobulk_df_tissue),
	iteration = "group",
	resources = pseudobulk_df_tissue$COLUMN_GB_PER_CORE
)
```

or

```r
tar_target(
	pseudobulk_df_tissue_merged,
	pseudobulk_df_tissue |> aggregate() |> map_quantile_scale_abundance() |>  se_add_dispersion(),
	pattern = map(pseudobulk_df_tissue),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew(COLUMN_GB_PER_CORE))
)
```

Thanks!

**Comment by wlandau** [comment]
Memory limits are handled through the `crew` controller you define in `_targets.R`. You could define a controller group with a high-memory and a low-memory controller for the different kinds of tasks you have, then assign each target to a controller from within `tar_resources_crew()`. Please have a look at https://books.ropensci.org/targets/crew.html#heterogeneous-workers and https://wlandau.github.io/crew/articles/groups.html.

In `crew`, there is not a 1:1 correspondence between tasks and workers. Each worker could run multiple tasks (as is usually the case). So it makes more sense for controllers within a controller group to have low-level resource settings like memory, then a higher-level way to assign each target to a controller.

**Comment by stemangiola** [comment]
(I read the documents) Sorry if I am missing something here, but there might be a need to assign 2 controllers (high, and low memory) for 1 target with

```r
pattern = map(<...>),
iteration = "group",
```

For complex pipelines, one target might be highly heterogeneous.

**Comment by wlandau** [comment]
Then I recommend grouping dynamic branches into different targets according to memory requirements. I have no plans to make resources dynamic.

**Comment by stemangiola** [comment]
Would it be something like the following, or there is a more elegant way?

```r
# Splitting (would this split duplicate data on the hard-drive I imagine?)
tar_targets(small_tasks, tasks |> filter(number_of_samples<=10)),
tar_targets(big_tasks, tasks |> filter(number_of_samples>10)),

# Executing
tar_target(
	small_result,
	small_tasks |> do_something(),
	pattern = map(small_tasks),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew("small_slurm"))
),
tar_target(
	big_result,
	big_tasks |> do_something(),
	pattern = map(big_tasks),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew("big_slurm"))
),

# Grouping back
tar_targt(result, bind_rows(small_result, big_result))

```

**Comment by stemangiola** [comment]
(I thought I found the solution in the documentation and deleted my comment, but I don't think so). Would it be something like

```r
# Splitting (would this split duplicate data on the hard-drive I imagine?)
tar_targets(small_tasks, tasks |> filter(number_of_samples<=10)),
tar_targets(big_tasks, tasks |> filter(number_of_samples>10)),

# Executing
tar_target(
	small_result,
	small_tasks |> do_something(),
	pattern = map(small_tasks),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew("small_slurm"))
),
tar_target(
	big_result,
	big_tasks |> do_something(),
	pattern = map(big_tasks),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew("big_slurm"))
),

# Grouping back
tar_targt(result, bind_rows(small_result, big_result))

```

or more compact

```r
# Filterign and Executing
tar_target(
	small_result,
	small_tasks |> filter(number_of_samples<=10) |> do_something(),
	pattern = map(small_tasks),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew("small_slurm"))
),
tar_target(
	big_result,
	big_tasks |> filter(number_of_samples>10) |> do_something(),
	pattern = map(big_tasks),
	iteration = "group",
	resources = tar_resources(crew = tar_resources_crew("big_slurm"))
),

# Grouping back
tar_targt(result, bind_rows(small_result, big_result))

```

**Comment by wlandau** [comment]
Either could work, but your first example might be better if it creates fewer branches. In the second example, you may end up with branches with no rows.
