### ISSUE TITLE
targets:::store_read_object.tar_aws_file - does not pass along endpoint - file targets fail to download

### ISSUE THREAD

**Issue by snowpong** [ropensci/targets#1138]
In the function [targets:::store_read_object.tar_aws_file()](https://github.com/ropensci/targets/blob/a906886874bc891cfb71700397eb9c29a2e1859c/R/class_aws_file.R#L56) it reads out `key, bucket, region` and `version` from the path object and passes it along to [aws_s3_download()](https://github.com/ropensci/targets/blob/a906886874bc891cfb71700397eb9c29a2e1859c/R/class_aws_file.R#L63), but it does not pass along `endpoint`.

This means that with custom endpoints (for example using MinIO with "http://127.0.0.1:9000" as the endpoint) a "file" target will fail to download (but upload is fine). A description on this problem can be [seen here](https://github.com/ropensci/targets/discussions/1134#discussioncomment-6873565). Essentially I get a _Could not resolve host: s3.NULL.amazonaws.com_

The call to aws_s3_download should have `endpoint = store_aws_endpoint(path)` added to it so the custom endpoint is respected.

In my setup I confirmed this solved the issue by forcing a break with `debug(targets:::store_read_object.tar_aws_file)` and running `targets::tar_read(my_file_target)` and then stepping into aws_s3_download and setting the custom endpoint that was not passed along manually.

**Comment by wlandau** [comment]
Thanks for the FYI. Should be fixed in 116f1ced90e1945bc0a6888e79c8600d097f0e99. Please let me know if it still doesn't work.

**Comment by snowpong** [comment]
Thank you. It now works!

tir. 5. sep. 2023, 02:01 skrev Will Landau ***@***.***>:
