### ISSUE TITLE
Add `tar_config_list()`?

### ISSUE THREAD

**Issue by psychelzh** [ropensci/targets#1153]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

When there are multiple projects, listing all the projects is especially useful when choosing which project to use.

**Comment by wlandau** [comment]
Thanks, added `tar_config_projects()` to list projects and `tar_config_yaml()` to read the whole yaml file.
