### ISSUE TITLE
`tar_debug()`?

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/targets#1161]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

A function called `tar_debug()` could run the targets necessary to run the target that has generated an error message and load the objects needed to run the code in the faulty target into the global environment. Can provide mode detail and reproducible example. My understanding is that `browser()` at the beginning of the target that generates an error would do the same job, but this would help automate that.

Thoughts?

**Comment by wlandau** [comment]
I have no plans to put all this together in one function, but you can accomplish this in pieces. `tar_make(names = all_of("TARGET_THAT_ERRORS"))` will run all the dependencies of the failing target, then try the target itself. You can combine this with `tar_option_set(debug = "TARGET_THAT_ERRORS")` and/or `tar_option_set(workspace_on_error = TRUE)`  for debugging purposes: https://books.ropensci.org/targets/debugging.html.
