### ISSUE TITLE
Allow users to manually set targets to done so they won't be recomputed

### ISSUE THREAD

**Issue by mcenno** [ropensci/targets#1169]
## Prework

* [X ] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [X ] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [X ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Sometimes it would be beneficial to have the opportunity to manually set a target to "done", so it and its dependencies won't be recomputed. For example, I have a configuration file which is the first target in a pipeline that runs for hours. If, after a successful run, I want to add a comment to the configuration file (without changing its relevant contents), the entire thing would need to run again. But all I want to do, really, is just to say `tar_mark_as_done(config)` or something along these lines.

A similar tool in Python, dvc, has the command `dvc commit` (https://dvc.org/doc/command-reference/commit) which pretty much does this.

**Comment by wlandau** [comment]
This is possible through `tar_target(cue = tar_cue(mode = "never"))`: https://docs.ropensci.org/targets/reference/tar_cue.html

**Comment by mcenno** [comment]
Thanks for your reply. If I understand `tar_cue()` correctly, I could temporarily add `cue=tar_cue(mode='never')` to the definition of `test`, but then I'd have to take it out after I've run the pipeline again. I didn't know this existed, so thanks for pointing it out.

So yes, the functionality exists, but not in an easily accessible `tar_<command>` way. Since all the machinery which marks a target as "done" exists and is called by `tar_make()` after completion anyway, wouldn't it be easy to expose it to the user, too, so s/he can mark a target as "done"?

I'd like that, but I also realise it may be a fringe application.
