### ISSUE TITLE
Cleaner "skipped branch" printing strategy for large (10000+ targets) pipelines 

### ISSUE THREAD

**Issue by stemangiola** [ropensci/targets#1222]
## Prework

* [  x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [ x ] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x ] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

### Description:

I am experiencing an issue with the verbosity of the console output when working with large target lists in my pipeline. This issue particularly affects the user experience in RStudio, where screen printing is notably slow.

### Current Behavior:

When a target list labeled a (with numerous entries such as a_f26dfc94, ..., a_c3b57e8c) has already been completed, restarting the pipeline results in an excessive amount of printouts. Each skipped target is individually reported, like so:

```r
✔ skipped branch a_f26dfc94
[...]
✔ skipped branch a_c3b57e8c
```

This process continues for all 10,000+ targets, eventually concluding with:

```r
✔ skipped pattern a
```

### Issue:

The sheer volume of these printouts (over 10,000) floods the console, leading to two main problems:

Screen Clutter: It becomes challenging to track other important outputs amidst the deluge of skip messages.

Performance Impact: In RStudio, the process of printing to the console is slow, which significantly delays the start of the pipeline.

### Proposed Solution:

Instead of printing a message for each skipped branch, it would be more efficient to display a single summary message indicating the entire pattern was skipped. For example:

```r
✔ skipped pattern a
```

This change would greatly enhance clarity, reduce clutter on the screen, and improve the startup time of the pipeline in RStudio.

**Comment by wlandau** [comment]
I suggest choosing a different `reporter` in `tar_make()`. Notably, `reporter = "verbose_positives"` and `reporter = "timestamp_positives"` omit the "skip" messages. And to avoid slowing down the pipeline due to lots of printing, you have the option to buffer these console messages and print e.g. at most every 10 seconds with `tar_make(seconds_reporter = 10)`. Another alternative is to call `tar_make(reporter = "silent")` to suppress all messages, `reporter = "summary"` to get just a high level view, and/or open a new R session and run `tar_poll()` to monitor updates.

**Comment by stemangiola** [comment]
I get this when I use `reporter="summary"`. Any was to omit "Submitted batch job ..."

```r
qs 0.25.6
queued | skipped | dispatched | completed | errored | warned | canceled | time       
26     | 8075    | 14         | 0         | 0       | 0      | 0        | 16:08 25.27Submitted batch job 15515158
Submitted batch job 15515159
Submitted batch job 15515160
Submitted batch job 15515161
Submitted batch job 15515162
Submitted batch job 15515163
Submitted batch job 15515164
Submitted batch job 15515165
Submitted batch job 15515166
Submitted batch job 15515167
Submitted batch job 15515170
Submitted batch job 15515174
Submitted batch job 15515176
25     | 8075    | 15         | 0         | 0       | 0      | 0        | 16:08 25.86Submitted batch job 15515179
11     | 8075    | 29         | 0         | 0       | 0      | 0        | 16:08 26.05Submitted batch job 15515186
Submitted batch job 15515187
Submitted batch job 15515188
Submitted batch job 15515189
Submitted batch job 15515190
Submitted batch job 15515191
Submitted batch job 15515192
Submitted batch job 15515193
Submitted batch job 15515194
Submitted batch job 15515195
Submitted batch job 15515196
Submitted batch job 15515197
Submitted batch job 15515198
Submitted batch job 15515199
10     | 8075    | 30         | 0         | 0       | 0      | 0        | 16:08 26.70Submitted batch job 15515200
39     | 8075    | 34         | 0         | 0       | 0      | 0        | 16:08 26.87Submitted batch job 15515216
Submitted batch job 15515219
Submitted batch job 15515221
Submitted batch job 15515224
Submitted batch job 15515225
70     | 8075    | 35         | 1         | 0       | 0      | 0        | 16:09 55.42Submitted batch job 15515454
Submitted batch job 15515457
68     | 8075    | 35         | 3         | 0       | 0      | 0        | 16:10 11.27Submitted batch job 15515504
66     | 8075    | 36         | 4         | 0       | 0      | 0        | 16:10 12.60Submitted batch job 15515505
Submitted batch job 15515506
60     | 8075    | 33         | 13        | 0       | 3      | 0        | 16:10 56.15Submitted batch job 15515534
60     | 8075    | 28         | 18        | 0       | 5      | 0        | 16:11 28.91
```

**Comment by wlandau** [comment]
Setting `verbose = FALSE` in the `crew` controller should work.
