### ISSUE TITLE
[ideas] `description` field for targets

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#1235]
### Discussed in https://github.com/ropensci/targets/discussions/1230, posted by @tjmahr

<div type='discussions-op-text'>

<sup>Originally posted by **tjmahr** February  9, 2024</sup>
### Help

- [X] I understand and agree to <https://books.ropensci.org/targets/help.html>.

### Description

Sometimes I wish I had an `description` field for documenting what each target it is a more human-friendly way. 

```
tar_target(
  name,
  command,
  description = "a field where we can briefly describe the target",
)
```

One could write a code comment, but this approach would be better because it could show up in `tar_manifest()`. It would also help generate READMEs.

Arguably, we should make the commands into simple functions and document those functions, but the trouble I have is having several end-products and recalling what they are. </div>

**Comment by wlandau** [comment]
Descriptions could also power a new way to select and group targets: https://github.com/ropensci/targets/discussions/1136 and https://github.com/ropensci/targets/discussions/1196

**Comment by jl5000** [comment]
Is there a way of retrieving descriptions for specific targets _within_ a pipeline (i.e. within a target's definition)?

**Comment by wlandau** [comment]
This currently works:

```r
  tar_target(
    name = target_name,
    command = tar_definition()$settings$description,
    description = "something"
  )
```

but the specific elements of `tar_definition()` are internals an may change in the future. So it's there for you to use, but at your own risk.
