### ISSUE TITLE
Let `targets::tar_make(reporter = "timestamp_positives")` report timestamps in local time zone

### ISSUE THREAD

**Issue by psychelzh** [ropensci/targets#1247]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Currently `targets::tar_make(reporter = "timestamp_positives")` reports timestamps in UTC rather than LTC, which is a little confusing. For example:

![image](https://github.com/ropensci/targets/assets/13306020/5c5f3ffb-d96a-403b-9ed6-7fee217aff3b)

But actual local time is +8.

![image](https://github.com/ropensci/targets/assets/13306020/70e46a73-3e40-4310-b811-a76a7db409e6)

Adding UTC as suffix or trying to add offset are both okay.

**Comment by wlandau** [comment]
Sounds reasonable, added a UTC suffix in 3dce80da95b0ac89da4cb953a8e5681627f64116

**Comment by dakvid** [comment]
Could I repeat the request for a local zone display option please? I understand the sense of a UTC default in a distributed environment, but for situations where there's only going to be one time zone it's a bit of a hindrance.

My production pipelines are using 1.4.0 and helpfully logging progress with local time:
![time_local](https://github.com/ropensci/targets/assets/16313131/842a23cb-7f6e-42f7-9cdd-ea599d98a7ac)
But I upgraded to 1.6.0 on my laptop today and discovered that times are now reported in UTC:
![time_utc](https://github.com/ropensci/targets/assets/16313131/3fc6c697-29d4-4081-9d42-50725260992c)
This will make examining the output log files quite annoying (even despite the advantage of a 12 hour difference for half the year :)

**Comment by wlandau** [comment]
Switched to the local time zone in e398c74ac060c0744c90f28a99ff9acb36480c8f.

**Comment by dakvid** [comment]
That's awesome, thanks!
