### ISSUE TITLE
the covr badge in README does not point to main

### ISSUE THREAD

**Issue by maelle** [ropensci/targets#1277]
It still points to master.

**Comment by wlandau** [comment]
Would you help me track that down? In `README.Rmd`, I see https://codecov.io/gh/ropensci/targets/branch/main:

https://github.com/ropensci/targets/blob/65a94c8b151217afd9407936deed2d2996b5c022/README.Rmd#L23

And in https://raw.githubusercontent.com/ropensci/targets/main/README.md, I see `[![codecov](https://codecov.io/gh/ropensci/targets/branch/main/graph/badge.svg?token=3T5DlLwUVl)](https://app.codecov.io/gh/ropensci/targets)`.

**Comment by wlandau** [comment]
It seems https://app.codecov.io/gh/ropensci/targets loads a page in codecov.io with "Branch Context" equal to "master". Odd that Codecov's does not detect changes to the default branch on GitHub. When I manually changed the default branch context to "main" in codecov settings, it looks to have taken hold.
