### ISSUE TITLE
allow reporter = "silent" for specific `tar_targets`

### ISSUE THREAD

**Issue by stemangiola** [ropensci/targets#1293]
## Prework

* [ x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [ x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

We are using Targets to make scalable APIs (HPCell). This pipeline is decided by the user, and we build a custom pipeline from the API calls, of this sort.

```step_1() > step_2() |> step_3() |> ...```

or

```step_1() > step_3() |> ...```

Sometime, targets are not defined, and it simplifies the implementation to create dummy targets (=NULL) anyway. However the messaging of a target (that should not exist) being build is confusing for the user.

it would be beneficial to have

```r
tar_target(normalisation, NULL, reporter = "silent")
```

so that such a target gets built but in the background.

Thanks.

**Comment by wlandau** [comment]
I don't have plans to redesign the `reporter` infrastructure to make this work there, but as long as you are developing a custom API, you could make use of `tar_progress()` and other functions in https://docs.ropensci.org/targets/reference/index.html#progress and filter out the `NULL` targets.
