### ISSUE TITLE
Return timestamps in tar_meta() as POSIXct

### ISSUE THREAD

**Issue by noamross** [ropensci/targets#131]
## Prework

* [x] I understand and agree to `targets`' [code of conduct](https://github.com/wlandau/targets/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Timestamps stored in `_targets/meta/meta` and returned in the `time` column of `tar_meta()` output are doubles, not a time format.  It seems to me the bulk of use cases of this data (e.g., triggering based on out-of-date targets) would make use of this in POSIXct format.  I'm not sure if there is a reason to avoid this in storage but it seems default behavior should be to return it in a date format.  Currently converting via `as.POSIXct()`, requires one to know the origin, and it isn't clear whether the origin comes from R or the filesystem and might not hold moving the cache across machines.

**Comment by wlandau** [comment]
The `time` column is for internal purposes rather than user benefit. The goal is performance: `targets` uses it to decide whether it can safely avoid rehashing files. If the file is sufficiently large and the current time stamp agrees with the one in the metadata, `targets` just looks up the old hash in the metadata.

If we us POSIX format, those time stamps will be converted to character strings in the metadata, and we will need to convert them back into PSOXct objects when we read the metadata back in. Based on past experience profiling `drake`, I strongly suspect this processing will show up as a speed bottleneck if we have a large number of targets and/or files. Sorry to disappoint.

**Comment by wlandau** [comment]
Wait, do you mean `tar_meta()` should do the conversion? Because that seems more reasonable.

**Comment by wlandau** [comment]
On the other hand, those doubles in the data are orphaned, so it may not be possible to convert them back:

``` r
x <- as.double(as.POSIXct("2020-01-01"))
as.POSIXct(x)
#> Error in as.POSIXct.numeric(x): 'origin' must be supplied
```

<sup>Created on 2020-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by noamross** [comment]
Right, the orphaning is the issue, conversion is otherwise a convenience (maybe something that can be done as a helper function in the **tarchetypes** package).  Right now I am setting up a trigger in `_targets.R` like so:

```
data_is_old <- as.POSIXct(meta[meta$name == "state_covid_rates",]$time, origin = '1970-01-01 00:00.00 UTC') < (Sys.time() - days(1))
tar_target(
    some_data,
    fetch_data(),
    cue = tar_cue(if_else(data_is_old, "always", "thorough")
)
```

While timestamps are for internal purposes I do think they should be available to the user for purposes such as this. I suppose they could also be retrieved by getting them from the filesystem, in which case another function could scan `_targets/objects` as well as any target paths to retrieve this info.

**Comment by wlandau** [comment]
I think the `data` hash would actually be better for this use case, especially if time stamps change when you copy the project from one file system to another.

**Comment by wlandau** [comment]
But it's usually better/cleaner to not have to manually look up the metadata to make build decisions. That's `targets`' job.

**Comment by noamross** [comment]
Well, for this case, when the target fetches data from an external web API, the data hash (of, say, the URL) doesn't tell us if the remote source has changed and I want to avoid re-fetching frequently.  This is similar to #130, in that I'm looking for a way to allow a custom cue depends on an external signal.

**Comment by wlandau** [comment]
That's helpful. Would you post a sketch of the pipeline? I feel optimistic that we can find a workaround.

**Comment by noamross** [comment]
Can you clarify?  The snippet above is sort of my sketch, though it makes an assumption about the date origin.  Do you mean a sketch of pulling the information from file timestamps? As you point out that's at least as brittle.

**Comment by wlandau** [comment]
Oops, you're right. I just glanced at it too quickly, sorry about that.

I think I see what you mean  now, hashes are overkill if you just want to know if your dataset is a day old. `file.mtime(tar_path(some_data))` (equivalent to `file.mtime("_targets/objects/some_data")`) is probably okay unless you plan on moving the project around a lot. Otherwise, maybe store `Sys.time()` inside the return value of `fetch_data()`, retrieve `tar_read(some_data)$your_timestamp`, and use the result to decide the cue.

**Comment by wlandau** [comment]
We might be able to simplify this with a new tarchetype. A tarchetypes::tar_remote() helper could generate a list of 2 targets: one to get the remote data and another downstream to record a posix timestamp. The cue definition of the upstream target could depend on the stored value of the downstream timestamp. @noamross, would this meet your need?

The potential role of branching here is still a little cloudy to me.

**Comment by noamross** [comment]
I'm just thinking of a few variations on this and how much they should be wrapped up together:

- For the the use case I'm grabbing data via an API client R package that doesn't give access to the HTTP headers.
-  I had been thinking of a `tar_download()` which would grab download file from a URL and incorporate the logic from **drake** for checking file modified time and eTag data from the HTTP header.  Setting an "age" option in this would make sense so that the target updates after a given age makes sense. 
- Other cases, such as hitting a database #130, would have some other, custom way of checking a remote source age or status that a user may want to use as a trigger. 

I think an archetype like `refreshing_target <- tar_refresh(my_target, interval)` that generates a pair of targets that refreshes would be useful for the first case.  A `tar_download()` option, which uses the header logic might be useful for the second, which could be wrapped in `tar_refresh()` if the user desires.  I'm not sure yet if there's a general approach for the last. Maybe `tar_triggered(my_target, function_that_always_runs_and_returns_logical_output)`?  This could produce a pair of targets, the first of which is the checking-function output and the second the target that would be triggered if this output changes?  But maybe that's just better as a documented example.

**Comment by wlandau** [comment]
After reading https://github.com/wlandau/targets/issues/131#issuecomment-668023819, I am starting to mentally connect more of the dots. I would prefer to first replicate the `condition` and `change` triggers with your general-use version of the two-target archetype (cc @jaredlander). Now that we have [`tarchetypes`](https://github.com/wlandau/tarchetypes), I think I now know how to do this in a way that correctly registers dependencies without needing to change anything in `targets` itself. Subsequent specialized archetypes such as remote file targets can build on top of them.

I will most likely disable branching (i.e. no `pattern` argument) at least until I am sure branching will not cause confusion.

**Comment by wlandau** [comment]
@noamross, https://github.com/wlandau/tarchetypes/issues/2 is now implemented. I think you will be able to work with timestamps using `tar_change(target_name, regular_command(), get_timestamp())`, where `get_timestamp()` rounds to the nearest day.

**Comment by wlandau** [comment]
Looking back, maybe there is a nicer workaround. What if `targets` were to set its own reference time? Time stamps for the metadata could be calculated like this:

```r
time <- file.mtime("some_file") # or for URLs, the time the target runs.
reference <- strptime("1960-01-01", format = "%Y-%m-%d", tz = "GMT")
diff_days <- difftime(time, reference, units = "days")
diff <- as.character(round(as.numeric(diff_days), 6))
```

Then `tar_meta()` and `tar_timestamp()` could convert back for the user.

```r
as.difftime(as.numeric(diff), units = "days") + reference
```

We need to make sure online formats like `format = "url"` and `format = "aws_parquet"` store a usable time in the metadata. Not all online formats will give a usable timestamp, so we can stick with the time the target runs or something.

cc @petrbouchal

**Comment by wlandau** [comment]
Note to self: run the [profiling studies](https://github.com/ropensci/targets/blob/main/tests/performance/test-maps.R) on all platforms to make sure this does not create a bottleneck.
