### ISSUE TITLE
Automatic detection of the low-level file system

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#1315]
`targets` primarily relies on hashes to detect changes in files, but to speed up computation, it sometimes uses time stamps to check if a hash is even worth calculating. I would like this to be default everywhere but some storage drives have formats like FAT which have imprecise time stamps. 

@gaborcsardi, @hadley mentioned you might know how to auto detect if a file system is [FAT, EXT, NFS, etc](https://en.wikipedia.org/wiki/List_of_file_systems). Is there a robust way to do this for an R package? If so, `targets` could deprecate `tar_option_set(trust_object_timestamps = TRUE)` and `format = "file_fast"`.

c.f. #1311

**Comment by gaborcsardi** [comment]
Yes, `ps::ps_disk_partitions()` will tell you the type of the file system, if that's all you need.

**Comment by hadley** [comment]
@gaborcsardi is there an existing helper to find the device that corresponds to a path? Or do you just find the longest `mountpoint` prefix that matches your path?

**Comment by gaborcsardi** [comment]
I don't know of a way from R. You need to call `statfs(2)` on Unix, IDK on Windows.

**Comment by gaborcsardi** [comment]
`ps_fs_info()` will now return file system information for one or more paths: https://github.com/r-lib/ps/pull/165
It finds the file system of the input files/directories automatically.

**Comment by wlandau** [comment]
> ps_fs_info() will now return file system information for one or more paths: https://github.com/r-lib/ps/pull/165
It finds the file system of the input files/directories automatically.

Awesome, thanks @gaborcsardi! This looks like exactly what I need.

> In Docker it is not very exciting

Not sure I follow. Is it because OverlayFS doesn't really tell us what the actual underlying file system is?

**Comment by wlandau** [comment]
I just added https://github.com/ropensci/targets/pull/1326 to (mostly) fix #1315. Still a few to-dos listed in the PR.

**Comment by wlandau** [comment]
Done in #1326

**Comment by rfineman** [comment]
Just a heads up (and really more of a comment for @gaborcsardi), this leads to some issues if you're running a targets pipeline as a kubernetes cronjob. Has to do with [ps_disk_partitions accessing /etc/mtab](https://github.com/r-lib/ps/blob/1e8305b0f5194d40f7bb854d2d5dde14dcca809b/src/api-linux.c#L1603C21-L1603C30). A current workaround I found  is to create a symbolic link between /proc/self/mounts and /etc/mtab, however I imagine there might be more graceful solutions.

**Comment by rfineman** [comment]
It doesn't exist in the kubernetes environment. Was a real pain to figure that out because it exists locally and in the docker container it was built with.

**Comment by gaborcsardi** [comment]
In general you have to be prepared that these calls might fail. Of course this is true in general, but even more true for functions in ps. E.g. some barebone Linux systems don't even have a `/proc` file system. I guess I could add this to the docs.

**Comment by wlandau** [comment]
> Just a heads up (and really more of a comment for @gaborcsardi), this leads to some issues if you're running a targets pipeline as a kubernetes cronjob. Has to do with [ps_disk_partitions accessing /etc/mtab](https://github.com/r-lib/ps/blob/1e8305b0f5194d40f7bb854d2d5dde14dcca809b/src/api-linux.c#L1603C21-L1603C30). A current workaround I found is to create a symbolic link between /proc/self/mounts and /etc/mtab, however I imagine there might be more graceful solutions.

What happens exactly? Is there a specific function in `ps` that throws an error?

**Comment by gaborcsardi** [comment]
IDK for sure, but `mtab` only appears once in the ps source code, so I guess it is an error here:
https://github.com/r-lib/ps/blob/1e8305b0f5194d40f7bb854d2d5dde14dcca809b/src/api-linux.c#L1603

**Comment by wlandau** [comment]
Thanks. In 06def2604e1646531f6da8e3af00b840c4d496f1, I have added error handling in `targets` around calls to `ps::ps_disk_partitions()` and `ps::ps_fs_mount_point()`. Hopefully that helps.

**Comment by rfineman** [comment]
From what I was able to ascertain, I agree with @gaborcsardi. On the `targets` side, the issue arises after calling `tar_make()` as under the hood it's using `runtime_file_systems` to get the file information which calls `ps::ps_disk_partitions()`. I've attached the traceback error. Hopefully https://github.com/ropensci/targets/commit/06def2604e1646531f6da8e3af00b840c4d496f1 will help.

`-- Last error traceback ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ tar_make(callr_function = NULL) callr_outer(targets_function = tar_make_inner, targets_arguments = targe... callr_dispatch(targets_function = targets_function, targets_arguments = ... if_any(is.null(callr_function), callr_inner(targets_function = targets_f... callr_inner(targets_function = targets_function, targets_arguments = tar... tryCatch(out <- withCallingHandlers(targets::tar_callr_inner_try(targets... tryCatchList(expr, classes, parentenv, handlers) tryCatchOne(expr, names, parentenv, handlers[[1L]]) doTryCatch(return(expr), name, parentenv, handler) withCallingHandlers(targets::tar_callr_inner_try(targets_function = targ... targets::tar_callr_inner_try(targets_function = targets_function, target... callr_set_runtime(script = script, store = store, fun = fun, pid_parent ... runtime_set_file_info(tar_runtime, store) trust_timestamps(store) runtime_file_systems() ps::ps_disk_partitions() not_null(.Call(ps__disk_partitions, all))`
