### ISSUE TITLE
add "niceNames" and "showAttributes" to deparse options 

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#1375]
Options "niceNames" and "showAttributes" have been part of `.deparseOpts()` since https://github.com/wch/r-source/blob/6363ed6d31e6b0637836728138f21fff5a126905/doc/NEWS.3.Rd#L1537-L1543. I think I was resistant to adding these initially because they seemed recent additions to R, but they have been around since R 3.5.0, which is the minimum version of `targets`. Adding them would improve the user experience for cases like https://github.com/ropensci/tarchetypes/issues/94.

**Comment by wlandau** [comment]
To elaborate: `targets` currently does this:

```r
deparse(structure(list(a = 1), class = "b"), control = c("keepNA", "keepInteger"))
#> [1] "list(1)"
```

I am proposing that it do this:

```r
deparse(structure(list(a = 1), class = "b"), control = c("keepNA", "keepInteger", "niceNames", "showAttributes"))
#> [1] "structure(list(a = 1), class = \"b\")"
```

This will make `tar_map()` and `tar_map_rep()` easier to use.

**Comment by psychelzh** [comment]
Thought this will make 64-bit integer works (i.e., bit64::integer64), but it does not. Will this make it possible? The following is an example:

``` r
targets::tar_dir({
    targets::tar_script({
        list(tarchetypes::tar_map(list(a = c(12, 34), b = bit64::as.integer64(c(45, 
            78))), targets::tar_target(x, a + b), targets::tar_target(y, 
            x + a, pattern = map(x))))
    })
    targets::tar_manifest()
})
#> Error:
#> ! Error in tar_manifest():
#>   a target name cannot end with a dot. Found: x_12_structure.2.22329540628561e.322..class...integer64.
#>   See https://books.ropensci.org/targets/debugging.html
```

<sup>Created on 2025-04-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by wlandau** [comment]
I'd recommend using the `names` argument of `tar_map()` to avoid output from deparsing `bit64::integer64()` objects.
