### ISSUE TITLE
Assign targets to families in order to refer them more easily

### ISSUE THREAD

**Issue by mattwarkentin** [ropensci/targets#208]
## Prework

* [x] Read and agree to the [code of conduct](https://github.com/wlandau/targets/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Hi @wlandau,

Just thinking out loud here, but would there be any interest in the ability to "tag" groups of targets as being especially related within the overall pipeline. I'm imagining this tagging would have no material affect except that it would get captured as a character vector column in `meta` and would allow one to refer to families of targets more simply.

This could be especially helpful when calling `tar_make()` or `tar_visnetwork()`, `tar_invalidate()` or other functions where you want to refer to a set of targets without referring to each by name. Perhaps something like:
```r
tar_pipeline(
  tar_target(
    raw,
    iris,
    family = "data"
  ),
 tar_target(
    clean,
    iris %>% filter(Species == "setosa"),
    family = "data"
  ),
 tar_target(
    fit,
    lm(Sepal.Length ~ Sepal.Width, data = clean),
    family = "model"
  ),
 tar_target(
    preds,
    predict(fit),
    family = "model"
  )
)

# To only build the data family of targets
tar_make(family = "data")
```
Targets could, in theory, belong to more than one family. This would be especially help in relation to #198, when I want to run different targets in different ways. Easier to refer to by family. Targets would build the fewest non-family targets as possible to build the family. This is already what happens when you request to build a single target that has upstream dependencies not listed in the call to `tar_make()`.

Pipeline dependencies are inferred from the DAG topology, whereas family dependencies would be arbitrarily constructed by the user.

I don't know exactly what NSE might be going on under the hood when the bare target name is captured, but maybe a simple syntax like the following would be concise and avoid adding more arguments:
```r
tar_target(
  name = family:target,
  command = expr
)
```
Where the target name is parsed for family and target names. I actually like this idea more, since I would like to avoid bloating `tar_target` with arguments that are not critical. Also I would guess this would avoid breaking existing code...

**Comment by yogevherz** [comment]
I'd like to jump in and say that I think this may indeed be a helpful idea, especially if you could add multiple tags. Using naming conventions and tidyselect is useful, but things can become messy when you want your target to belong to more than one group. 

For example, say I'm creating several models and each has a train stage. So I can name them `model1_train`, `model2_train` etc. I can tidyselect targets either by model name (`tar_load(starts_with("model1")`) or stage (`tar_load(ends_with("train")`), but this method doesn't scale so well when I have multiple attributes per target and it can limit how informative a name I can give (because I'm constrained by naming conventions that will work with tidyselect).

It would be easier to scale if instead I could define tags for each target, something like:
```
tar_pipeline(
  tar_target(model1_train,
             train(model1),
             tags = c("model1", "training")),
  tar_target(model2_train,
             train(model1),
             tags = c("model2", "training")),
)
```
And just call targets using tags, for example:
```
tar_load(tags = "training")
```

**Comment by wlandau** [comment]
I see your point about scale, but I think the need is not strong or common. It does not seem worth redesigning the interface or working through the potential ambiguities.

**Comment by mattmoo** [comment]
I am also reaching the sensible limits of what can be done by string matching a variable name. A simple wrapper accomplishes most of what I would like to use, but of course I don't know that much about the overall architecture.


```
# R/functions.R
get_data <- function(file) {
  airquality %>%
    filter(!is.na(Ozone))
}

fit_model <- function(data) {
  lm(Ozone ~ Temp, data) %>%
    coefficients()
}

plot_model <- function(model, data) {
  ggplot(data) +
    geom_point(aes(x = Temp, y = Ozone)) +
    geom_abline(intercept = model[1], slope = model[2])
}

# Wrapper
tar_target = function(..., tags = NULL) {
  stem = targets::tar_target(...)
  stem$settings$tags = tags
  return(stem)
}
  
# Pipeline
library(targets)
tar_option_set(packages = c("readr", "dplyr", "ggplot2"))
target_list = list(
  tar_target(data, get_data()),
  tar_target(model, fit_model(data), tags = 'model'),
  tar_target(plot, plot_model(model, data))
)
```

```
mask_vector = unlist(lapply(target_list, function(x) 'model' %in% x$settings$tags))
target_name_vector = unlist(lapply(target_list[mask_vector], function(x) x$settings$name))
tar_make(target_name_vector)
```
