### ISSUE TITLE
Is error message accessible with error="continue" 

### ISSUE THREAD

**Issue by liutiming** [ropensci/targets#267]
Is error message accessible with error="continue"? As far as I can see it is not printed to the console.

Also, https://docs.ropensci.org/targets/'s manual link is broken...  :(

**Comment by wlandau** [comment]
> Is error message accessible with error="continue"? As far as I can see it is not printed to the console.

It is available in the metadata. Maybe it should be relayed as a message.

``` r
library(targets)
tar_script({
  tar_option_set(error = "continue")
  options(crayon.enabled = FALSE)
  list(
    tar_target(data1, stop("error_data1")),
    tar_target(data2, stop("error_data2"))
  )
})

tar_make()
#> ● run target data1
#> x error target data1
#> ● run target data2
#> x error target data2
#> ● end pipeline

tar_meta(starts_with("data"), error)
#> # A tibble: 2 x 2
#>   name  error      
#>   <chr> <chr>      
#> 1 data1 error_data1
#> 2 data2 error_data2
```

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> Also, https://docs.ropensci.org/targets/'s manual link is broken...

`targets` and `tarchetypes` got moved today, but I am still waiting on permission to send `targets-manual` and `targets-design` to their rOpenSci homes (probably `github.com/ropensci-books`). The links are

**Comment by wlandau** [comment]
Should be fixed now:

``` r
library(targets)
tar_script({
  tar_option_set(error = "continue")
  options(crayon.enabled = FALSE)
  list(
    tar_target(data1, stop("error_data1")),
    tar_target(data2, stop("error_data2"))
  )
})

tar_make()
#> ● run target data1
#> x error target data1
#> Error: error_data1
#> ● run target data2
#> x error target data2
#> Error: error_data2
#> ● end pipeline

tar_meta(starts_with("data"), error)
#> # A tibble: 2 x 2
#>   name  error      
#>   <chr> <chr>      
#> 1 data1 error_data1
#> 2 data2 error_data2
```

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by liutiming** [comment]
great thanks!

**Comment by liutiming** [comment]
Hi Will, I found the fix very helpful, but it may be even better if the error can be displayed at the end of the pipeline like warnings do. Now I have to scroll up to find the error message (of course if I am testing a pipeline I should have used "stop" option instead.

**Comment by wlandau** [comment]
I think errors should be displayed as soon as possible so users can stop the pipeline early, and repeating the error messages at the end seems a bit much. The current behavior aligns with R's existing default behavior so people know what to expect. (And warnings can be printed sooner with `options(warn = 2)`).

**Comment by liutiming** [comment]
ok thanks!
