### ISSUE TITLE
clustermq will not respond to higher per target resource specification on a cluster?

### ISSUE THREAD

**Issue by liutiming** [ropensci/targets#268]
To confirm:

If my understanding is correct, once a `clustermq` worker has been submitted as a job, the maximum amount of resources is already allocated at the time of submission. Thus, for per target resource specified via `resources=list` that require more resources than what was initially submitted, its requirements will not be entertained.

Thus, the option is only useful for 
1. `future` which submits one job for each target or 
2. for scaling down the resource requirement in each target (although I do not see much point doing this, since the thread will be occupied anyways) or 
3. for a local computer that has more resources than what was initially asked.

**Comment by wlandau** [comment]
That's correct. The `resources` argument of `tar_target()` is ignored for the purposes of `clustermq` workers. Users need to go through `tar_option_set()` to set `clustermq` resources. Target-specific HPC template values will only be filled in for `tar_make_future()`, as you described. But there are other uses for `resources` in general, such as specifying an S3 bucket name or the compression settings for `fst` and `qs` formats.
