### ISSUE TITLE
Is there a best practice for tracking databases in targets?

### ISSUE THREAD

**Issue by MxNl** [ropensci/targets#269]
## Prework

Currently, I need to do some calculations in a postgres database, which I execute from within a targets pipeline.
Regarding the tracking of the tables in the database I read this issue related to drake: https://github.com/ropensci-books/drake/issues/46

## Question

Is there any targets specific update on best practises when working with databases? And if so, how would you do it?
Thanks once more for these great packages!

**Comment by wlandau** [comment]
The issues are unfortunately still the same in `targets`. The challenge is that each target is an immutable artifact, whereas databases are designed to change in place. In most cases, I would recommend that you pull the raw data you need from the database such that the target automatically invalidates when the database table changes. `tarchetypes::tar_force()` might help.

```r
tar_force(raw_data, get_data_from_postgress(), force = date_last_modified())
```

where `get_data_from_postgress()` and `date_last_modified()` are custom functions. You could alternatively replace `date_last_modified()` with a custom `hash_of_table()` to track the hash of the postgres table instead.

**Comment by muschellij2** [comment]
The `force` argument expects a logical, so make sure `date_last_modified()` returns that otherwise `any` `POSIXt` errors.
