### ISSUE TITLE
tar_read static branch targets

### ISSUE THREAD

**Issue by liutiming** [ropensci/targets#271]
Hi Will,

I am wondering if there is a way to `tar_read` static branch targets as a list? Currently the names are suffixed with values in `tar_map` and the target name in `tar_script` cannot be recognized by `tar_read`.

**Comment by liutiming** [comment]
I realised this might be what tar_combine is for... let me try

**Comment by liutiming** [comment]
Unfortunately I do not think it works - one still has to type out all the target names that are not in the target script... any suggestions?

**Comment by wlandau** [comment]
`tar_read()` is always one-by-one (except for dynamic branching) but you can use `tar_load()` with `tidyselect` syntax. `tar_map()` usually creates targets with common prefixes (and you can adopt this convention yourself if you use `tar_eval()`). That lets you use `tar_load(starts_with("common_prefix"))`.

**Comment by liutiming** [comment]
`tar_load` is a good call but I am not sure if it fulfills the use case. The ideal case is that targets can create a named list for static branched targets using something like `tibble::lst()` so that when

**Comment by wlandau** [comment]
You can make `tar_load()` behave like a list of `tar_read()`s.

```r
envir <- new.env()
tar_load(starts_with("prefix"), envir = envir)
as.list(envir)
```

I am not sure I will build this in as a feature because it overlaps with existing functionality that generalizes better.

**Comment by liutiming** [comment]
I see thanks! I think there will still be a use case for loading objects in literate programming with `tar_read`. Just some food for thought

**Comment by liutiming** [comment]
Just to add to this, I find it quite amusing that the targets name gets longer and longer through the pipeline to indicate each processing done, and suddenly at the final stage it needs to be drastically shortened to be used for static branching and to avoid names that are incomprehensible. I find a mixed use of camelCase and snake_case helped though it breaks the tidyverse style guide a bit...

**Comment by wlandau** [comment]
If you use `tar_map()`, the `names` argument might help with this. `names` understands tidyselect syntax to choose a subcollection of `values` to construct target names. If you want fully custom suffixes, supply a totally custom column of `values` and name it in `names`. And of course `tar_eval()` can assign full names directly without appending suffixes.

**Comment by liutiming** [comment]
Hi @wlandau, I find myself using static branching more and more frequently. I wonder if it is a good idea to have a function like `tar_read_branches` to read all the branches of a static branch target?

**Comment by wlandau** [comment]
Once the static branches are created, `targets` no longer keeps track of where those branches came from. As we discussed, `tar_load()` with `tidyselect` already acts like `tar_load_branches()` would, and this covers `tar_read()`-like situations too.

**Comment by wlandau** [comment]
To clarify: by design, all `tar_make()` and related functions know about is the target names. After `tar_map()`, you get a nested list of target objects, and that list is flattened out in the pipeline. The nesting is the only other possible source of information about how static branches are related, and it is not reliable information because nested target lists can be created in other ways, and it is not a good architectural fit to track it anyway. Target names are the best source of information on how static branches are related, and `tidyselect` functionality is a convenient way to work with that information.

**Comment by liutiming** [comment]
Thanks for the reply! I can see where you are coming from. I guess I can just write a snippet for `tar_load(starts_with("$1"))` or something similar. 

I guess the main idea I am proposing is to treating the `_targets.R` script like a user interface to their data (at least this is how I use it, by using shortcuts to load snippets of selected variables and print out data instead of writing the full variable name every time I use it). It it is ideal to maintain the purity of targets package, it will be a helpful rstudio/vscode add-on to have all the helper shortcuts (I believe @milesmcbain has very useful snippets here https://github.com/MilesMcBain/vsconfig).
