### ISSUE TITLE
How to define file targets with multiple outputs

### ISSUE THREAD

**Issue by joelnitta** [ropensci/targets#272]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

I am trying to design workflows that rely primarily on linking input and output files through various external programs (a very common task in my field, bioinformatics). There are many existing tools for this (e.g., [nextflow](https://www.nextflow.io/), [CWL](https://www.commonwl.org/)), but it would be great for me as an R-user to do this with `targets`.

To this end, I need to be able to track input and output files consistently. This is straightforward with `tar_file()` if there is only a single input and output, but it becomes more complicated if multiple output files are produced and/or used as dependencies.

In the example below, `remove_letters()` produces two output files. If I manipulate it so that only one output file is different (e.g., by changing `out1 <- str_remove_all(lines, "i")` to `out1 <- str_remove_all(lines, "o")` and re-run the workflow, `targets` runs both `mid_a` and `mid_b` even though the only file that has changed is `"output_A1.txt"`, not `"output_B1.txt"`. I assume this is because changing any part of `remove_letters()` invalidates all of `letters_removed`, even though I know it only changes one part of the output. This may seem like a minor point, but it could be important in a real workflow where a single step could be very computationally expensive and I want to avoid re-running steps whenever possible. I have also tried using `tar_files()` and `tar_files_input()` for the step that produces `letters_removed`, but they all re-run both `mid_a` and `mid_b`. 

Is there a way to set this up so that a change in output of one file within a vector of filenames triggers only building of targets that depend on that particular file?

On a related note: is there a more compact way to specify a single file within a character vector of file names? I tried returning a named vector from the function, but when I inspected it with `tar_load()` or `tar_read()`, the names of the vector were `NULL`.

## Reproducible example

``` r
targets::tar_dir({
  targets::tar_script({
    # Load libraries
    library(targets)
    library(tarchetypes)
    suppressPackageStartupMessages(library(tidyverse))
    # Define some example functions that take files as input and output
    remove_letters <- function (file_in, file_out1, file_out2) {
      lines <- read_lines(file_in)
      out1 <- str_remove_all(lines, "i")
      out2 <- str_remove_all(lines, "f")
      write_lines(out1, file_out1)
      write_lines(out2, file_out2)
      c(file_out1, file_out2)
    }
    to_caps <- function (file_in, file_out) {
      read_lines(file_in) %>%
        str_to_upper() %>%
        write_lines(file_out)
      file_out
    }
    to_lower <- function (file_in, file_out) {
      read_lines(file_in) %>%
        str_to_lower() %>%
        write_lines(file_out)
      file_out
    }
    # Define targets
    list(
      tar_file(
        letters_removed, 
        remove_letters(
          file_in = "https://gist.githubusercontent.com/joelnitta/859eb3a0983e5bc6a192f3ed03672f8d/raw",
          file_out1 = "output_A1.txt",
          file_out2 = "output_B1.txt")
      ),
      tar_file(
        mid_a, 
        to_caps(
          file_in = letters_removed[letters_removed == "output_A1.txt"],
          file_out = "output_A2.txt")
      ),
      tar_file(
        final_a,
        to_lower(
          file_in = mid_a,
          file_out = "output_A3.txt"
        )
      ),
      tar_file(
        mid_b, 
        to_lower(
          file_in = letters_removed[letters_removed == "output_B1.txt"],
          file_out = "output_B2.txt")
      ),
      tar_file(
        final_b,
        to_caps(
          file_in = mid_b,
          file_out = "output_B3.txt"
        )
      )
    )
  })
  # Make targets
  targets::tar_make()
  
  # Modify one of the functions and repeat
  targets::tar_script({
    library(targets)
    library(tarchetypes)
    suppressPackageStartupMessages(library(tidyverse))
    remove_letters <- function (file_in, file_out1, file_out2) {
      lines <- read_lines(file_in)
      out1 <- str_remove_all(lines, "o") # <--This change only affects "output_A1.txt"
      out2 <- str_remove_all(lines, "f")
      write_lines(out1, file_out1)
      write_lines(out2, file_out2)
      c(file_out1, file_out2)
    }
    to_caps <- function (file_in, file_out) {
      read_lines(file_in) %>%
        str_to_upper() %>%
        write_lines(file_out)
      file_out
    }
    to_lower <- function (file_in, file_out) {
      read_lines(file_in) %>%
        str_to_lower() %>%
        write_lines(file_out)
      file_out
    }
    
    list(
      tar_file(
        letters_removed, 
        remove_letters(
          file_in = "https://gist.githubusercontent.com/joelnitta/859eb3a0983e5bc6a192f3ed03672f8d/raw",
          file_out1 = "output_A1.txt",
          file_out2 = "output_B1.txt")
      ),
      tar_file(
        mid_a, 
        to_caps(
          file_in = letters_removed[letters_removed == "output_A1.txt"],
          file_out = "output_A2.txt")
      ),
      tar_file(
        final_a,
        to_lower(
          file_in = mid_a,
          file_out = "output_A3.txt"
        )
      ),
      tar_file(
        mid_b, 
        to_lower(
          file_in = letters_removed[letters_removed == "output_B1.txt"],
          file_out = "output_B2.txt")
      ),
      tar_file(
        final_b,
        to_caps(
          file_in = mid_b,
          file_out = "output_B3.txt"
        )
      )
    )
  })
  # Make targets
  targets::tar_make()
})
#> [34m●[39m run target letters_removed
#> [34m●[39m run target mid_a
#> [34m●[39m run target mid_b
#> [34m●[39m run target final_a
#> [34m●[39m run target final_b
#> [34m●[39m end pipeline
#> [34m●[39m run target letters_removed
#> [34m●[39m run target mid_a
#> [34m●[39m run target mid_b
#> [34m●[39m run target final_a
#> [32m✓[39m skip target final_b
#> [34m●[39m end pipeline
```

<sup>Created on 2021-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] igraph_1.2.6       knitr_1.30         magrittr_2.0.1     tidyselect_1.1.0  
#>  [5] R6_2.5.0           rlang_0.4.10       fansi_0.4.2        stringr_1.4.0     
#>  [9] highr_0.8          tools_4.0.3        targets_0.0.2.9000 data.table_1.13.6 
#> [13] xfun_0.19          cli_2.2.0          withr_2.4.0        ellipsis_0.3.1    
#> [17] htmltools_0.5.0    yaml_2.2.1         digest_0.6.27      assertthat_0.2.1  
#> [21] lifecycle_0.2.0    tibble_3.0.5       crayon_1.3.4       processx_3.4.5    
#> [25] purrr_0.3.4        callr_3.5.1        vctrs_0.3.6        ps_1.5.0          
#> [29] codetools_0.2-16   glue_1.4.2         evaluate_0.14      rmarkdown_2.6     
#> [33] stringi_1.5.3      pillar_1.4.7       compiler_4.0.3     renv_0.11.0       
#> [37] pkgconfig_2.0.3
```

</details>

**Comment by wlandau** [comment]
In your example, each of `mid_a` and `mid_b` depends on all of `letters_removed`. That is why any change in `letters_removed` invalidates both `mid_a` and `mid_b`.

![Screen Shot 2021-01-19 at 8 10 26 AM](https://user-images.githubusercontent.com/1580860/105038831-d0eaa980-5a2d-11eb-8e2d-946439b16f0f.png)

To get the invalidation behavior you want, we need to split `letters_removed` into two different targets first. As long as it does not take long to hash the files, this should be okay.

```r
# _targets.R
...
list(
  tar_file(
    letters_removed, 
    remove_letters(
      file_in = "https://gist.githubusercontent.com/joelnitta/859eb3a0983e5bc6a192f3ed03672f8d/raw",
      file_out1 = "output_A1.txt",
      file_out2 = "output_B1.txt"
    )
  ),
  tar_file(begin_a, letters_removed[1]), # new target to just get output_A1.txt and track it as a file
  tar_file(begin_b, letters_removed[2]), # same for output_B1.txt
  tar_file(
    mid_a, 
    to_caps(
      file_in = begin_a,
      file_out = "output_A2.txt")
  ),
  tar_file(
    mid_b, 
    to_lower(
      file_in = begin_b,
      file_out = "output_B2.txt")
  ),
  ...
)
```

![Screen Shot 2021-01-19 at 8 13 38 AM](https://user-images.githubusercontent.com/1580860/105039344-71d96480-5a2e-11eb-9dc4-899cc70c3223.png)

`tar_files()` and `tar_files_input()` use a similar technique internally.

**Comment by joelnitta** [comment]
Thanks! That definitely makes sense 👍
