### ISSUE TITLE
Best practice to extend dataset and reduce targets duplication

### ISSUE THREAD

**Issue by liutiming** [ropensci/targets#281]
Hi @wlandau, what do you think will be the best practice to extend an existing targets pipeline to a new dataset (but can fit in the same analysis?)

`tar_map` seems to be the best option to reduce targets duplication, but that has some inconveniences  I raised earlier https://github.com/ropensci/targets/issues/271 and targets will probably re-run the whole pipeline given all the name changes?

copy-paste all targets and add suffix to the second set results in duplication - harder to keep both in sync...

Use a git like solution https://github.com/ropensci/targets/issues/255 will not allow us to easily compare the results from these two datasets?

Would love to hear your thoughts on this and really appreciate!

**Comment by liutiming** [comment]
One more option is to combine two datasets as a new target using `tar_target(x, list(t1, t2))`, but the tricky bit is that many downstream targets are probably not prepared to taken in a list and it will be tricky to add and combine patterns in all downstream targets.

**Comment by wlandau** [comment]
Sounds like you may have better luck with `tarchetypes::tar_eval()`, which is more flexible than `tar_map()`. The example below is simple, but `tar_eval()` can also accept whole lists of input targets.

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  tar_target(x, identity(mtcars))
})

tar_make()
#> ● run target x
#> ● end pipeline

tar_script({
  library(tarchetypes)
  options(crayon.enabled = FALSE)
  tar_eval(
    tar_target(name, identity(dataset)),
    values = list(
      name = rlang::syms(c("x", "y")),
      dataset = list(quote(mtcars), quote(head(mtcars)))
    )
  )
})

tar_manifest(fields = command)
#> # A tibble: 2 x 2
#>   name  command               
#>   <chr> <chr>                 
#> 1 x     identity(mtcars)      
#> 2 y     identity(head(mtcars))

tar_make()
#> ✓ skip target x
#> ● run target y
#> ● end pipeline
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Unfortunately, metaprogramming gets very complicated very fast.

If you find yourself using the same kind of pipeline for the same kind of analysis repeatedly across many projects, maybe consider encapsulating all that in a new [R Targetopia package](https://wlandau.github.io/targetopia/contributing.html). rOpenSci will release a tech note next week which will say more about target factories. Here is a temporary preview: https://deploy-preview-122--ropensci.netlify.app/technotes/2021/02/03/targets/

**Comment by liutiming** [comment]
Thanks so much! The tech guide is very well written and thanks for the acknowledgement! It is very kind of you to pull out our websites and link them there. 

I think given that I have written dozens of targets to analyze one dataset, the most practical thing to do is probably to create a target factory to be used internally and when I move on to the next project I will follow the guide and write a targetopia package for existing target factories.

**Comment by liutiming** [comment]
`tar_eval` is an awesome idea! But it looks like I will have to rename all those targets that I have written, which is an undertaking and may not be a long-term solution?

```r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  list(
  tar_target(x, identity(mtcars)),
  tar_target(x_final, head(x)))
})

tar_make()
#> ✔ skip target x
#> ✔ skip target x_final
#> ✔ skip pipeline

tar_script({
  library(tarchetypes)
  options(crayon.enabled = FALSE)
  tar_eval(
    tar_target(name, identity(dataset)),
    tar_target(name_final, head(name)),
    values = list(
      name = rlang::syms(c("x", "y")),
      dataset = list(quote(mtcars), quote(head(mtcars)))
    )
  )
})

tar_manifest(fields = command)
#> # A tibble: 2 x 2
#>   name  command               
#>   <chr> <chr>                 
#> 1 x     identity(mtcars)      
#> 2 y     identity(head(mtcars))

tar_make()
#> ✔ skip target x
#> ● run target y
#> ● end pipeline
```
Created on 2021-01-26 by the reprex package (v0.3.0)

``` r
library(targets)
tar_script({
  options(crayon.enabled = FALSE)
  list(
  tar_target(x, identity(mtcars)),
  tar_target(x_final, head(x)))
})

tar_make()
#> ● run target x
#> ● run target x_final
#> ● end pipeline

tar_script({
  library(tarchetypes)
  options(crayon.enabled = FALSE)
  tar_eval(
    tar_target(name, identity(dataset)),
    tar_target(name_final, head(name)),
    values = list(
      name_final = rlang::syms(c("x", "y")),
      dataset = list(quote(mtcars), quote(head(mtcars)))
    )
  )
})

tar_manifest(fields = command)
#> Error : duplicated target names: name
#> Error: callr subprocess failed: duplicated target names: name

tar_make()
#> Error : duplicated target names: name
#> Error: callr subprocess failed: duplicated target names: name
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Yeah, as you said, `tar_eval()` is just a stopgap, and `name_final` would need to be micromanaged as well as `name`.

**Comment by liutiming** [comment]
Thanks a lot!

**Comment by robertdj** [comment]
Stumbled across this question while searching for a good way to do something similar. I want to re-run an analysis every week extended with last week's data. Every week I want to start from the same origin, so I only add data. 

To only download the missing data I have a manual "cache" where the data from each week is stored in a separate `qs` file.
My "download target" only download data from weeks that are not downloaded already. However, I don't explicitly make {targets} aware of my "cache".
I'm not sure that this is the best approach and I wonder if {targets} facilitate such a usecase? Or maybe I have missed tools that support my approach :-)

**Comment by wlandau** [comment]
Maybe `tarchetypes::tar_force()`, where the `condition` is the most recent week with data? Or an upstream `tar_url(cue = tar_cue(mode = "always"))` that points to the URL of the most recent dataset and is upstream of the download target. Either way, the target that downloads the current week could be a `format = "file"` target that returns the directory with all the downloaded files so far.. Hashing might get expensive when files accumulate, but you select a subset if you do not care about reproducibly tracking them all.

**Comment by robertdj** [comment]
I'll try that out -- thanks for you suggestions!
