### ISSUE TITLE
Compatibility with Shiny

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#291]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Let's make it easier to write Shiny apps that run `targets` pipelines behind the scenes. This will require some new features and a chapter in the manual.

### Parameterized target scripts

A Shiny app with a `targets` pipeline should have a central `_targets.R` script. This file should live at the root of the app code, and its contents must not change when the app runs. However, the __pipeline__ needs to change based on inputs from the app user: for example, to use a different set of R scripts to populate functions or construct the targets themselves. 

To programmatically modify pipelines from the calling R process, we can support parameterized `_targets.R` files. The `targets` user (app developer) would set/get parameters in the calling process (Shiny session). Then, `targets` would substitute them inline into a temporary copy of `_targets.R`, and then run that temporary copy. Parameters should be small character strings of length 1. I know some people will want to substitute more text - for example, entire pipeline definitions - but in those cases, it is better to define those targets as external scripts and pass the paths as parameters instead.

~~### Script helpers~~

~~`tar_script()` helps write `_targets.R`, but apps might need to write other R scripts dynamically. A new `tar_helper()` function could assist with this.~~

### Set the path to the data store

Originally, I wanted the data store to always live at `_targets/` in the project root. However, that does not bode well for Shiny apps because we cannot write to the local app code. The best current workaround is to wrap every call `tar_make()` etc. in `withr::with_dir()`, but this leads to uncertainty and inconsistency. In this situation (but not many others) it is better to let the user set the path. This requires a new `path_store` option (`tar_option_set(path_store = ...)`) which gets forwarded to targets that build on HPC workers (in case the user selects storage/retrieval on workers).

### User storage helpers

The `tools` package in R >= 4.0 supports a nice `R_user_dir()` function for persistent user-specific data, configuration, and cache files. And if we conditionally import it from `backports` (with [`@rawNamespace`](https://blog.rstudio.com/2015/10/29/roxygen2-5-0-0/)) then we can use it in earlier versions of R. Some wrappers would help manage app storage for multiple sessions across multiple users.

* `tar_user_dir(id = "main")`: short for `file.path(tools::R_user_dir(), id)`, where `id` is a session ID.
* `tar_user_path(path, id = "main")`: short for `file.path(tools::R_user_dir(), id, path)`.
* `tar_user_store_get(id = "main")`: short for `tar_user_path("_targets", id = "main")`
* `tar_user_store_set(id = "main")`: short for `tar_option_set(path_store = tar_user_store_get(id))`.

**Comment by wlandau** [comment]
We also need #292.

**Comment by wlandau** [comment]
Also, let's hold off on script helpers for now. I do not actually know if we will need them.

**Comment by wlandau** [comment]
For the example app that will come out of this, we should look at authentication. We will need some way to differentiate among users so we can assign them different storage spaces.

**Comment by wlandau** [comment]
I propose `glue(readLines("_targets.R"), .open = "<tar>", close = "</tar>")` to substitute parameters. The "tar" prefix is already ubiquitous, and the HTML syntax is recognizable, and the open/close delimiters are not likely to conflict with anything already in R.

**Comment by mattwarkentin** [comment]
Maybe [`moustache`](https://github.com/edwindj/whisker) could be helpful here? Developers could write parameterized `_targets.R` files and the Shiny app inputs can be used to fill in the blanks.

This suggestion may be way off, as I'm only guessing what you're looking for.

**Comment by wlandau** [comment]
That's basically the idea, but I have a lot of trust in `glue` specifically, and there is a risk of ambiguity with legitimate R code if I use curly braces. Notably, `{{` is an `rlang` tidy evaluation operator.

**Comment by mattwarkentin** [comment]
`glue` is great! I'm just trying to keep up my streak of suggesting multiple bad ideas until eventually a good one arrives.

**Comment by wlandau** [comment]
Please keep chiming in. All brainstorming is good brainstorming.

**Comment by wlandau** [comment]
A couple more notes:

1. We probably want `<param>...</param>` tags instead of `<tar>...</tar>` because the former are more immediately recognizable as parameters, especially for folks who have used parameterized R Markdown.
2. User storage helpers are probably unnecessary. We can just point to `tools::R_user_dir()` in the docs and manual. Shiny developers will not necessarily write to `R_user_dir("targets/a/b/c")` because most apps do not run as the app user.

**Comment by wlandau** [comment]
Taking a step back, `tar_option_set(path_store = ...)` still does not feel right because

1. It needs to be set both inside `_targets.R` and in the calling process. Otherwise, `tar_read()` and friends will not work because they do not run `_targets.R`.
2.  There is already so much demand for this feature that it will definitely be misappropriated in non-Shiny situations and reproducibility will definitely suffer.
3. There is an extra maintainer burden because the storage options would need to get passed to HPC workers.

And I do not think other mechanisms will work. For example, if we rely on an environment variable, that environment variable will need to be parameterized based on the Shiny session, which is awkward and even more of a maintainer burden.

# New plan

1. Implement parameterization for `_targets.R` files.
2. Keep #292.
3. Forgo custom cache paths. Always keep the cache at `_targets/` in the project root next to `_targets.R`.
4. Forgo the proposed user helpers like `tar_user_dir()`.
5. Write a couple examples of `targets`-powered Shiny apps: one with a user login and user storage, one with temp storage and no login. These will live in separate repos and have RStudio Cloud workspaces similar to https://github.com/wlandau/targets-minimal.
6. Throughout the code in the above apps, use `withr::with_dir()` to temporarily change the working directory whenever we need to invoke `targets`.
7. Write an example in the [manual](https://github.com/ropensci-books/targets) to summarize and teach what we learn implementing (5) and (6).

(5) though (7) are for separate repos. (1) is enough to close the issue.

**Comment by wlandau** [comment]
Because of https://github.com/ropensci/targets/issues/291#issuecomment-773742633, the app's user/temp storage needs to have a mutable copy of `_targets.R` anyway. That means folks can just use [`brew`](https://CRAN.R-project.org/package=brew) for parameterized scripts of any kind. There is no longer anything to do in `targets` itself, the work will all be in the documentation.

When I get time, I will work on a couple example apps, then a chapter in the manual after I hit the obvious unknown unknowns.

**Comment by wlandau** [comment]
FYI: just released a prototype app with a `targets` backend: https://github.com/wlandau/targets-shiny. Shows how to create powerful data pipelines inside apps.
