### ISSUE TITLE
.lintr config is for lintr < v2

### ISSUE THREAD

**Issue by russHyde** [ropensci/targets#295]
## Prework

* [+] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [+] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [+] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Please describe the issue.

To help us read any code you include (optional) please try to follow the [tidyverse style guide](https://style.tidyverse.org/). The `style_text()` and `style_file()` functions from the [`styler`](https://github.com/r-lib/styler) package make it easier.

## Reproducible example

* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

The linters `snake_case_linter` and `camel_case_linter` have been deprecated in {lintr} and were removed from the set of default linters provided by that package prior to lintr v2 (ie, earlier than the current CRAN release of lintr, which targets uses in CI).

In the config, the line `snake_case_linter=NULL` originally would have prevented newly-named objects that are not 'snake_case' from throwing an object-naming lint.

To permit snake-case vars you would now use `object_name_linter("snake_case")` in the config, but I noted that object_name_linter has also been NULL-ed out (so, naming issues do not throw lints during targets' CI runs)

Since these linters are now deprecated, they can be removed from your lintr config without any effect.

**Comment by wlandau** [comment]
Fixed in #294. Thanks for the PR.
