### ISSUE TITLE
deployment = "local" was removed and it breaks tar_target()

### ISSUE THREAD

**Issue by brunocarlin** [ropensci/targets#298]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Please describe the issue.

Hi, I don't know if this is just me ranting about wasting a few minutes but I think the depreciation of the 

```
 tar_target(
    raw_data_file,
    "data/raw_data.csv",
    format = "file",
   deployement = "local"
  )


```

Giving error 

```
Error in match.arg(deployment, c("worker", "main")) : 
  'arg' should be one of "worker", "main"
Error: callr subprocess failed: 'arg' should be one of "worker", "main"
Type .Last.error.trace to see where the error occured


.Last.error.trace 
 Process 16000:
 19. (function (targets_script, targets_function, targets_arg ...
 20. base:::source(targets_script)
 21. base:::withVisible(eval(ei, envir))
 22. base:::eval(ei, envir)
 23. base:::eval(ei, envir)
 24. targets:::tar_target(raw_data_file, "data/raw_data.csv", ...
 25. base:::match.arg(deployment, c("worker", "main"))
 26. base:::stop(gettextf("'arg' should be one of %s", paste( ...
 27. base:::.handleSimpleError(function (e)  ...
 28. h(simpleError(msg, call))



```

Is not very clear, maybe an argument with a better message would have been better, I know this is just the initial stages of a great project but still...

As always thanks for the great package!

To help us read any code you include (optional) please try to follow the [tidyverse style guide](https://style.tidyverse.org/). The `style_text()` and `style_file()` functions from the [`styler`](https://github.com/r-lib/styler) package make it easier.

## Reproducible example

* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

You can fork the r targets-minimal to test or just change any target you have to include deployment = "local"

**Comment by brunocarlin** [comment]
Just to be clear I do have some experience reading these tracebacks and found on line 25 the relevant issue, but it is just not as friendly as the errors we get on some packages like dplyr

**Comment by wlandau** [comment]
Sorry about that. I was less concerned about breaking changes before `targets` achieved its first CRAN release. The error message should be better now.

``` r
targets::tar_target(x, 1, deployment = "local")
#> Error: deployment equals "local" but must be in c("worker", "main")
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
