### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by jrosen48** [ropensci/targets#308]
## Prework

* [x ] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x] Confirm that your issue is most likely a genuine bug in the `targets` package itself and not a user error or known limitation. For usage issues and troubleshooting, please post to the [discussions](https://github.com/ropensci/targets/discussions) instead.
* [ ] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

`targets::tar_make()` returns:

```
Error: main functions like tar_make() require a special _targets.R script in the current working directory to define the pipeline. Fucntions tar_edit() and tar_script() can help.
```

Please describe the bug.

Functions is spelled incorrectly as fucntions.

**Comment by wlandau** [comment]
Thanks.
