### ISSUE TITLE
Helper to deploy pipeline on GitHub Actions

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#339]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

`tar_github_actions()` should write https://github.com/wlandau/targets-minimal/blob/main/.github/workflows/targets.yaml to `.github/workflows/targets.yaml` and just work out of the box for workflows that do not need to scale (or low-compute workflows using format = "aws*" for the heavy data). cc @jaredlander

**Comment by jaredlander** [comment]
Just gave it a quick glance. Super awesome. It looks like it uses Mac runners. Is it possible to make it run in Ubuntu? That will probably be more in line with more people's expectations and will be much cheaper to run.

**Comment by wlandau** [comment]
Good point about cost. Linux will also bode well in the long term once `future` and/or `clustermq` get some kind of cloud compute support and `targets` can send off remote jobs via Actions. Still keeping the Mac system dependency step to make it easy to switch back.
