### ISSUE TITLE
tar_target(..., pattern = map(x), iteration = "list") should return named list object

### ISSUE THREAD

**Issue by HanjoStudy** [ropensci/targets#344]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

`tar_target(..., pattern = map(x), iteration = "list")` should return named list object if names are provided. Current output only provides unnamed list.

```{R}
# _targets.R
library(targets)

list(
  tar_target(
    x,
    list(my_list_1 = "hallo", my_list_2 = "goodbye"),
    iteration = "list"
  ),
  tar_target(z, x, pattern = map(x), iteration = "list")
)
```

Now lets run `tar_make()` and see the output:

```{R}
tar_make()
> tar_read(z)
[[1]]
[1] "hallo"

[[2]]
[1] "goodbye"
```

Preferably the output should contain the specified names within the `tar_target` named `x`:
```{R}
tar_make()
> tar_read(z)
$my_list_1
[1] "hallo"

$my_list_2
[1] "goodbye"
```

**Comment by wlandau** [comment]
If we were to preserve names, we would need to consider what happens when we branch over more than one target, which is not so simple.

```r
# _targets.R
library(targets)
library(tarchetypes)
source("R/functions.R")
list(
  tar_target(w, list(name1 = "value1", name2 = "value2"), iteration = "list"),
  tar_target(x, list(name_a = "value_a", name_b = "value_b"), iteration = "list"),
  tar_group_by(y, mtcars, cyl, drat),
  tar_target(z, my_function(w, x, y), pattern = map(w, x, y), iteration = "list")
)
```

For the element names of `z`, we would not only need a way to concatenate the element names of `w` and `x`, but also deal with the fact that `y` follows "group" iteration and has no names. The resulting names would be messy and not very useful. As long as you are using `"list"` iteration, I recommend adding any metadata you need as elements or attributes of the list elements themselves.

Related: https://github.com/ropensci/targets/issues/126

**Comment by ZekeMarshall** [comment]
Perhaps not an elegant workaround but I am making each mapped list element a named list of length 1, see below. I then just use `purrr::map_depth(<target>, 1, purrr::pluck(<mapped_var>))` in subsequent pipeline functions to retrieve the relevant elements.

![image](https://github.com/user-attachments/assets/2cbe3e1e-ade4-487c-94db-be786a351db4)

I would be interested to hear about other workarounds!
