### ISSUE TITLE
Global reporter option

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/targets#345]
I'd like to propose a global `reporter` option. This way I can set `options(targets.reporter = "summary")` in my .Rprofile once and not worry about running into `print()`-pocalypse if I forget to specify the `reporter` in a project with many targets/branches.

**Comment by wlandau** [comment]
Good idea. Just implemented a `TAR_MAKE_REPORTER` environment variable to set the reporter of `tar_make()`, `tar_make_clustermq()`, and `tar_make_future()`. (`targets` has no global options, but it does have other environment variables like `TAR_ASK` and `TAR_WARN`.)

**Comment by wlandau** [comment]
FYI: I am about to replace `TAR_MAKE_REPORTER` with `tar_config_get("reporter_make")`. The YAML config system is solid enough now for that, and this change help `targets` not be as dependent on the current R session.

**Comment by alexpghayes** [comment]
This is very nice. Should I be specifying project-level options via the `_targets.yaml` file, or by calling `tar_config_set()` in my `_targets.R` file? (It might be nice to add some documentation about this -- I found the current document unclear).

**Comment by wlandau** [comment]
Either way is fine. `tar_config_set()` is just another way to write `_targets.yaml` while validating user inputs.

**Comment by dipterix** [comment]
Is there any way to support `options(targets.reporter = ...)` with customized reporters that inherit `reporter_class`?

**Comment by wlandau** [comment]
You can set this with the `reporter_*` arguments of `tar_config_set()`.

**Comment by dipterix** [comment]
I thought `reporter_make` accepts characters. Is there any way that I can write my own reporter classes and use them to report the progress? For example, a shiny progress bar, or sending emails when some targets are resolved.

**Comment by wlandau** [comment]
Those reporter classes are completely internal, but you can periodically poll one of the [progress functions](https://docs.ropensci.org/targets/reference/index.html#progress) in a separate R session.
