### ISSUE TITLE
How to setup a shiny app as an end product of a  pipeline

### ISSUE THREAD

**Issue by dewoller** [ropensci/targets#351]
Hi William and allies.  Thanks for all the work you have put into targets.  I did not know that Drake could be so much improved, with so little work on my part. 

I have a pipeline that I have transferred to targets from Drake, and there is a shiny app at the end of the pipeline.  I use the same basic setup described in this article:

https://www.r-bloggers.com/2020/07/using-drake-for-etl-and-building-shiny-app-for-900k-ct-real-estate-sales/

Specifically, the plan looks like this:
```
# Our drake plan 
the_plan <-
  drake::drake_plan(
    raw_99_11 = try(load_raw_data()),
    cleaned_01_recent = load_socrata(),
    new = merge_and_clean_sources(
      raw_99_11,
      cleaned_01_recent
    ), 
    save_file = saveRDS(new, file_out("ct_sales_99_2018.RDS")),
####################################################################
# The following bit is the section I want to replicate using targets
####################################################################
    deployment = rsconnect::deployApp(
      appFiles = file_in(
        "ct_sales_99_2018.RDS",
        "app.R",
        "R/plot_dotplot.R",
        "R/plot_spaghetti.R",
        "R/plot_timeplot.R"
      ),
      appName = "ct_real_assess",
      forceUpdate = TRUE
    )
####################################################################
# end part
####################################################################
  )

```

Is it possible to have this functionality with targets?  Another alternative in Drake is to pass the appDir parameter through file_in, and storing all the shiny data and components in this directory.  How can I use all the files in a directory as the trigger for a target?

Thanks

**Comment by wlandau** [comment]
Yes, this is still possible. The major difference is you have [dynamic input/output files](https://books.ropensci.org/targets/files.html#external-input-files) instead of `file_in()`/`file_out()`.

* Example code: https://github.com/wlandau/targets-stan/blob/e3eba1e55a30461a8b1901d220eb64085df0fe09/_targets.R#L73-L79
* Live coding video: https://www.youtube.com/watch?v=Gqn7Xn4d5NI time 41:35 - 50:12
