### ISSUE TITLE
Documentation about random seeds and reproducibility

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/targets#357]
I would love to understand a little more about how targets sets random seeds. I see that I can query `tar_seed()`, but I would like to understand things just enough to be able to justify the reproducibility of my simulations (in terms of random seeds) to journal referees if they ask :). Is there any chance you could add a short section on this to the user manual?

**Comment by wlandau** [comment]
I just added some more documentation in the help files. The `name` argument of `tar_target()` and `tar_target_raw()`, the Details sections of `tar_seed()`, and the `fields` argument of `tar_meta()` now to explain seed generation. Hopefully that clears things up.

**Comment by alexpghayes** [comment]
Thank you, it does!
