### ISSUE TITLE
Warn against devtools::load_all() in _targets.R

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#374]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Users should not use `devtools::load_all()` or similar to load packages for `targets` pipelines. It is best to fully install the packages using `install.packages()` or equivalent and set the `packages` and possibly `imports` options as described at https://books.ropensci.org/targets/practices.html#loading-and-configuring-r-packages and https://books.ropensci.org/targets/practices.html#packages-based-invalidation. Reasons:

1. The loaded package will not be available on parallel workers created by `tar_make_clustermq()` or `tar_make_future()`.
2. If the goal is to load your [custom functions](http://books.ropensci.org/targets/functions.html) for the pipeline instead of `source("R/functions.R")`, then these functions will live in a special package environment where `targets` does not find them by default. Unless you also set the `imports` option, `tar_visnetwork(targets_only = FALSE)` will not show them, and `tar_make()` will not rerun the correct targets when you change your functions.

There is not much we can do here except education, but we can at least try to statically crawl through `_targets.R` and throw a warning if symbols like `load_all` are detected. This warning should be suppressed if `Sys.getenv("TAR_WARN")` is `"false"`.

**Comment by mdneuzerling** [comment]
Hi @wlandau. I suspect the links in the warning need to be updated. [https://books.ropensci.org/targets/practices.html#loading-and-configuring-r-packages](https://books.ropensci.org/targets/practices.html#loading-and-configuring-r-packages) leads to a 404. Perhaps [https://books.ropensci.org/targets/packages.html#loading-and-configuring-r-packages](https://books.ropensci.org/targets/packages.html#loading-and-configuring-r-packages) is the intended URL?

I can put a PR together for this tomorrow if you'd like.

**Comment by wlandau** [comment]
Thanks @mdneuzerling, 3e138e23cf6a843ae589186c07a401240075390f updates the links.

**Comment by gorgitko** [comment]
Hi @wlandau, do you think this partially simulates `devtools::load_all()` and bypass its shortcomings mentioned in this PR?

```r
# _targets.R in package root
# First load packages ("import()") and individual objects ("importFrom()") from the NAMESPACE file
for (imp in parseNamespaceFile(".", ".")$imports) {
  if (length(imp) == 1) {
    library(imp, character.only = TRUE)
  } else {
    import::from(imp[[1]], imp[[2]], .character_only = TRUE)
  }
}

# And then objects from R/
for (file in fs::dir_ls("R/")) {
  source(file, local = .GlobalEnv)
}
```

**Comment by wlandau** [comment]
To load scripts from within `_targets.R`, the current recommendation is `tar_source()`. For interactive/exploratory work outside the pipeline, you can use `tar_load_globals()` to load all the packages and functions.
