### ISSUE TITLE
Supporting DESCRIPTION file as dependency source

### ISSUE THREAD

**Issue by malcolmbarrett** [ropensci/targets#376]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

We manage our projects with `DESCRIPTION` files (and use an explicit caching approach in renv that looks for dependencies in that file). It's relatively easy to read `DESCRIPTION` on the fly and tell targets about it, but it would be great to have an out-of-box solution. 

(This is a separate issue, but we're inching towards a "pseudo-package" structure that deals with the limitations of using packages for projects while keeping the benefits. That effort overlaps with your recent warning about `load_all()`. We don't use that approach--we have a custom function that sources files--but I think it might be useful to explore a targets-based solution, as well.)

This could perhaps be an additional argument to `tar_options_set()` or a helper function to read the DESCRIPTION file and pass to the `packages` argument. Either way, this would likely be a simple wrapper around `desc::desc_get_deps()`, which would need to be added to targets' `Suggests`. 

I'm happy to work on a PR if you think this is useful.

**Comment by wlandau** [comment]
I think this is a good fit for a package like [`tflow`](https://github.com/MilesMcBain/tflow) or [`tarflow`](https://github.com/toddgrabowsky/tarflow). For `targets` itself, I generally try to keep most built-in features agnostic to project/file organization styles. The major exception is `tar_renv()`, which depends on internal objects. And `tar_github_actions()` may move one day.

**Comment by malcolmbarrett** [comment]
Ah, I see. That's reasonable. Thanks! Unfortunately, I don't think it's a good fit for those packages myself, so I'll have to think about that, e.g. if I'd want to open source our targets workflow code
