### ISSUE TITLE
tar_progress_summary()

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#380]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

`tar_progress_summary()` should return a one-line data frame with the number of built, started, canceled, and errored targets. In addition, it should show columns to reflect when there was last a change to progress: one `POSIXct` value for the last modified time of `_targets/meta/progress`, and another column to show how long ago that was.

**Comment by wlandau** [comment]
Implemented.

**Comment by psychelzh** [comment]
Is it possible to add "todo" column to optionally show number of targets not dispatched yet?

**Comment by wlandau** [comment]
Yeah, that would be convenient, but `tar_progress_summary()` unfortunately does not have access to this information because it is not running from the R process that the pipeline is running. That's why `tar_progress()` and `tar_progress_summary()` do not know the number of dispatched targets, where as `tar_make(reporter = "summary")` does know.

**Comment by psychelzh** [comment]
Thanks! Then `tar_progress_summary()` could be less helpful. I am often confused about how many targets remain to be processed with these functions, especially when dynamic branches are used. For example, I have used `tar_outdated()`, it reports confusing numbers when dynamic branches are used. Are there better options?
