### ISSUE TITLE
Don't use shinycssloaders in tar_watch

### ISSUE THREAD

**Issue by rcorty** [ropensci/targets#386]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

The shiny app launched by `tar_watch` updates every few seconds (5 by default). While the update is in process, the network is replaced by a "loading image" (from package shinycssloaders). As this update takes about 1 second, I think it would be more useful to leave the native shiny behavior during the update - continue to show the image that is about to be replaced. It's visually jarring to have the image continually disappearing and reappearing.

**Comment by wlandau** [comment]
Great point, @rcorty. `shinybusy` is a good replacement for `shinycssloaders`. Should be fixed now.
