### ISSUE TITLE
Error when sourcing {knitr} hooks in a rendered RMarkdown file

### ISSUE THREAD

**Issue by pgstevenson** [ropensci/targets#387]
## Description

When I include the code to set {knitr} hooks in an .Rmd the document it renders fine, but when I include the script it with `source("hook.R")` this error is thrown:

> Error: callr subprocess failed: object 'params' not found

## Reproducible example

This code reproduces the problem, the 3 files are in the same directory, and `targets::tar_make()` is used to implement the workflow. Un-comment the code from default_source_hook onwards and the workflow works.

### _targets.R

```
library(targets)
library(tarchetypes)
    
list(
  tar_target(dat, mtcars),
  tar_render(report,
             "report.Rmd",
             params = list(your_param = dat))
)
```

### hook.R

```
default_source_hook <- knit_hooks$get('source')
knit_hooks$set(
  source = function(x, options) {
    if(is.null(options$table))
      default_source_hook(x, options)
    else {
      eval(parse(text = x)) %>%
        kable("html", escape = FALSE) %>%
        kable_styling("hover", full_width = FALSE)
    }

  })
```

### report.Rmd:

    ---
    title: "Untitled"
    output: html_document
    params:
      your_param: NA
      
    ---
    
    ```{r, include = FALSE}
    
    library(knitr)
    library(kableExtra)
    
    source("hook.R")
    
    # default_source_hook <- knit_hooks$get('source')
    # knit_hooks$set(
    #   source = function(x, options) {
    #     if(is.null(options$table))
    #       default_source_hook(x, options)
    #     else {
    #       eval(parse(text = x)) %>%
    #         kable("html", escape = FALSE) %>%
    #         kable_styling("hover", full_width = FALSE)
    #     }
    # 
    #   })
    
    ```
    
    ```{r, table = TRUE, results = "hide", eval = FALSE}
    params$your_param
    ```

## Diagnostic information

    > sessionInfo()
    R version 4.0.4 (2021-02-15)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 8.1 x64 (build 9600)
    
    Matrix products: default
    
    locale:
    [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
    [3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
    [5] LC_TIME=English_Australia.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] targets_0.2.0
    
    loaded via a namespace (and not attached):
     [1] igraph_1.2.6      rstudioapi_0.13   knitr_1.31        magrittr_2.0.1    tidyselect_1.1.0 
     [6] R6_2.5.0          rlang_0.4.10      fansi_0.4.2       tools_4.0.4       data.table_1.14.0
    [11] xfun_0.22         utf8_1.2.1        cli_2.3.1         withr_2.4.1       htmltools_0.5.1.1
    [16] ellipsis_0.3.1    yaml_2.2.1        assertthat_0.2.1  digest_0.6.27     tibble_3.1.0     
    [21] lifecycle_1.0.0   crayon_1.4.1      processx_3.4.5    purrr_0.3.4       callr_3.5.1      
    [26] vctrs_0.3.6       ps_1.6.0          codetools_0.2-18  evaluate_0.14     glue_1.4.2       
    [31] rmarkdown_2.7     compiler_4.0.4    pillar_1.5.1      pkgconfig_2.0.3   

    > traceback()
    8: stop(error_run(...))
    7: throw_run(conditionMessage(e), "\nVisit https://books.ropensci.org/targets/debugging.html ", 
           "for debugging advice.")
    6: value[[3L]](cond)
    5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
    4: tryCatchList(expr, classes, parentenv, handlers)
    3: tryCatch(callr_dispatch(targets_function, targets_arguments, 
           callr_function, callr_arguments), callr_error = function(e) {
           throw_run(conditionMessage(e), "\nVisit https://books.ropensci.org/targets/debugging.html ", 
               "for debugging advice.")
       })
    2: callr_outer(targets_function = tar_make_inner, targets_arguments = targets_arguments, 
           callr_function = callr_function, callr_arguments = callr_arguments)
    1: targets::tar_make()

**Comment by wlandau** [comment]
`source("hook.R", local = environment())` fixes the issue because `targets` runs things in its own environment in order to prevent modifications to the global state. In general, it is best to set up all the global objects and functions from `_targets.R` and define targets that do not produce global side effects, but unfortunately `source("hook.R")` in `_targets.R` renders the report without the data frame.
