### ISSUE TITLE
Rename file written by tar_renv()

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#397]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is most likely a genuine bug in the `targets` package itself and not a user error, a known limitation, or a bug in another package that targets depends on. For miscellaneous troubleshooting, please post to the [discussions](https://github.com/ropensci/targets/discussions) instead.
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

The latest `renv` ignores the `_packages.R` file written by `tar_renv()`. Easy to check with `renv::dependencies()`. The name `_targets_packages.R` seems to work, so let's go with that.

**Comment by petrbouchal** [comment]
@wlandau looking at https://github.com/rstudio/renv/issues/698, could it be that `tar_renv()` is now unnecessary?

**Comment by wlandau** [comment]
I think it still is necessary because of package dependencies that come from other places. For example, if you define a target with `tar_target(.., format = "aws_parquet")`, then `tar_renv()` will make sure you have packages `aws.s3` and `arrow`. In addition, there are various other `Suggests:` packages required by `tar_make_clustermq()` and `tar_watch()` that `tar_renv()` detects.

**Comment by wlandau** [comment]
Still, I like https://github.com/rstudio/renv/issues/698 because it will catch a lot of simple cases
