### ISSUE TITLE
Add `check_region = TRUE` to aws.s3 calls to automatically determine the AWS region of an object

### ISSUE THREAD

**Issue by tomsing1** [ropensci/targets#400]
Thank you so much for making this awesome package available!

I use S3 buckets in multiple AWS regions, which makes relying on a single global `AWS_DEFAULT_REGION` environmental variable a bit tricky.

I found the `check_region` argument from the `aws.s3::s3HTTP` function really helpful. `s3HTTP` executes the calls to the AWS endpoints wrapped by `aws.s3::save_object` etc. The `check_region` argument can be added to all of the wrapper functions and is passed through to the eventual `s3HTTP` call. It automatically chooses the correct region for the S3 object even if the `AWS_DEFAULT_REGION` is unset or wrong (for the specified object).

From the [aws.s3 documentation](https://www.rdocumentation.org/packages/aws.s3/versions/0.3.21/topics/s3HTTP):

- `check_region`: A logical indicating whether to check the value of region against the apparent bucket region. This is useful for avoiding (often confusing) out-of-region errors. Default is `FALSE`.

Would this be a useful addition to the `aws.s3::save_object`, `aws.s3::delete_object`, `aws.s3::put_object`, etc calls, for example this one?

https://github.com/ropensci/targets/blob/2854580ba357a5b3ec750774484d86fef9ed29e0/R/class_aws.R#L43

(Happy to propose a pull request if you are interested.)

**Comment by wlandau** [comment]
Great suggestion! This makes total sense, especially since `targets` does not actually create any S3 buckets. Now implemented.
