### ISSUE TITLE
Cannot continue tar_make_clustermq() if all workers already shut down

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#404]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is most likely a genuine bug in the `targets` package itself and not a user error, a known limitation, or a bug in another package that targets depends on. For miscellaneous troubleshooting, please post to the [discussions](https://github.com/ropensci/targets/discussions) instead.
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

This bug was introduced by #398 and #399. After all workers correctly shut down early, `targets` keeps trying to communicate with them.

## Reproducible example

``` r
library(targets)
packageDescription("targets")$GithubSHA1
#> [1] "22f7c5f32ce890362324d72af8d51e201b728342"
tar_script({
    library(targets)
    options(clustermq.scheduler = "multicore")
    tar_option_set(deployment = "main")
    list(
        tar_target(index, seq_len(4)),
        tar_target(run, index, pattern = map(index), deployment = "worker"),
        tar_target(end, run)
    )
})

tar_make_clustermq()
#> ● start target index
#> ● built target index
#> ● start branch run_77ba9815
#> ● built branch run_77ba9815
#> ● start branch run_4b7abfa4
#> ● built branch run_4b7abfa4
#> ● start branch run_f5a3cbc2
#> ● built branch run_f5a3cbc2
#> ● start branch run_b0df9eb8
#> ● built branch run_b0df9eb8
#> ● built pattern run
#> ● end pipeline
#> Error in self$crew$receive_data() : 
#>   Trying to receive data after work finished
#> Error: callr subprocess failed: Trying to receive data after work finished
#> Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

## Expected result

The pipeline should have kept going locally without error.

**Comment by wlandau** [comment]
Need to manually decrement `self$workers` every time we shut down a worker and then check the worker count after that.

**Comment by wlandau** [comment]
cc @pat-s

**Comment by pat-s** [comment]
Thanks Will, that will me help me a lot for future projects with {targets}!

Thinking about whether I should port the project in which I discovered this from {drake} to {targets} or not.
It has more than 400 targets which is why I did not do it yet...
