### ISSUE TITLE
pkgdown build fails with rlang error

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#430]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is most likely a genuine bug in the `targets` package itself and not a user error, a known limitation, or a bug in another package that targets depends on. For miscellaneous troubleshooting, please post to the [discussions](https://github.com/ropensci/targets/discussions) instead.
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Hi @jeroen, I just encountered what looks like another instance of https://github.com/ropensci/targets/issues/422. The pkgdown site builds locally but https://dev.ropensci.org/blue/organizations/jenkins/drake/detail/drake/133/pipeline fails with what looks like an `rlang` error.

**Comment by jeroen** [comment]
@wlandau docs should be fixed now. I also removed the dev version of rlang from our universe, because it is causing a lot of problems.

**Comment by wlandau** [comment]
Thanks, @jeroen!
