### ISSUE TITLE
Function to support rapid prototyping of targets by emulating the pipeline build environment

### ISSUE THREAD

**Issue by mattwarkentin** [ropensci/targets#431]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Hi @wlandau,

So here is the workflow I often find myself in, when building a target, such as `tar_target(baz, foo(bar))`:

1. Manually load any packages I think will be needed for `foo()` to run
1. Write `foo()` such that will accept `bar` as an argument
1. Manually `tar_load()`/`tar_read()` the target dependency (`bar`) while I prototype, so I can test drive the function before calling `tar_make()`
1. Function seems to be working fine, call `tar_make()`, target builds fine
1. At some future time, I want to update the target `baz`, and so I again need to manually load necessary packages (inevitably forgetting one on the first try) and `tar_load()` all of the upstream targets I need to test the updated function

This is sort of annoying and repetitive and slows down rapid prototyping of my functions/targets. Workspaces are amazing, but it would be great to have that same feature for fast interactive prototyping.

Here is my thoughts/proposal:

- A function that works very similarly to `tar_workspace()` but is meant for interactive development, not debugging. 
- I propose `tar_emulate()`, a function for loading packages, functions, and upstream targets to enable rapid prototyping
- `tar_emulate()` would accept the `name` of a target (and optionally a branch), and will (by default) load packages required for the target and load any necessary functions/upstream targets into the global environment so you can prototype a target quicker.
```r
# Example API, based on tar_workspace()
tar_emulate(
  name,
  branches = NULL,
  envir = global_env(),
  packages = TRUE,
  source = TRUE
)
```

Based on the toy example below, when deciding to work on `b`, calling `tar_emulate(b)` would load `{tidyverse}` and `a` for me. In other words, it emulates the pipeline build environment for `b` in my global environment.
```r
# _targets.R

tar_option_set(
  packages = "tidyverse"
)

list(
  tar_target(a, mtcars),
  tar_target(b, foo(a))
)
```
Thoughts?

**Comment by wlandau** [comment]
It's a nice thought, but because of dynamic branching, this feature is actually harder than it would seem at first glance. We would need some way to ensure that emulation uses the correct set of upstream branches. This is tricky because some branches may be out of date, others may not exist yet, and some may no longer be applicable if the user changes the pipeline in a way that decreases the number of branches. So emulation would require traversing the whole pipeline up to the target you want to actually run interactively. That brings us right back to the [non-workspace interactive debugging functionality](https://books.ropensci.org/targets/debugging.html#the-debug-option) that already exists.
