### ISSUE TITLE
tar_read returns "Error: `..1` must be a vector, not an igraph object"

### ISSUE THREAD

**Issue by robitalec** [ropensci/targets#468]
## Prework

* [X] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [X] Confirm that your issue is most likely a genuine bug in the `targets` package itself and not a user error, known limitation, or bug in another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [X] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [X] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [X] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [X] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

`tar_read` returned this error instead of returning the `igraph` objects. I wasn't specifically interested in returning all the graphs (as in `tar_read(graphs)`) but I would hope to investigate separate graphs (as in `tar_read(graphs, branches = 1)`). 

`tar_load` returns the same error. 
I have tried this with the `format = 'qs'` option as well and the same error comes up. 

I identified the error using chunks of a data.table with `iteration = 'group'` (as described [here](https://github.com/ropensci/targets/discussions/395)) passing them through a few packages to make graphs (similar to [here](https://github.com/robitalec/targets-spatsoc-networks)). 

## Reproducible example

`_targets.R`

```r
# Packages
library(targets)
library(igraph)

list(
	tar_target(
		matrices,
		list(matrix(sample(0:1, 100, replace=TRUE, prob=c(0.9,0.1)), nc=10),
				 matrix(sample(0:1, 100, replace=TRUE, prob=c(0.75,0.1)), nc=10)),
		iteration = 'list'
	),
	tar_target(
		graphs,
		graph_from_adjacency_matrix(matrices),
		map(matrices)
	)
)
```

```r
> targets::tar_make()

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

✓ skip target matrices
✓ skip branch graphs_453e9959
✓ skip branch graphs_53a5f423
✓ skip pipeline
 
> tar_read(graphs)
Error: `..1` must be a vector, not a <igraph> object.
Run `rlang::last_error()` to see where the error occurred.
> tar_read(graphs, 1)
Error: `..1` must be a vector, not a <igraph> object.
Run `rlang::last_error()` to see where the error occurred.
> tar_read(graphs, 2)
Error: `..1` must be a vector, not a <igraph> object.
Run `rlang::last_error()` to see where the error occurred.
```

## Diagnostic information

```r
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.14.so
LAPACK: /usr/lib/liblapack.so.3.9.1

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] targets_0.4.2.9000

loaded via a namespace (and not attached):
 [1] codetools_0.2-18  fansi_0.4.2       ps_1.6.0         
 [4] withr_2.4.2       crayon_1.4.1      utf8_1.2.1       
 [7] digest_0.6.27     R6_2.5.0          lifecycle_1.0.0  
[10] magrittr_2.0.1    pillar_1.6.1      rlang_0.4.11     
[13] cli_2.5.0         rstudioapi_0.13   data.table_1.14.0
[16] callr_3.7.0       vctrs_0.3.8       ellipsis_0.3.2   
[19] tools_4.1.0       glue_1.4.2        purrr_0.3.4      
[22] igraph_1.2.6      yaml_2.2.1        compiler_4.1.0   
[25] processx_3.5.2    pkgconfig_2.0.3   tidyselect_1.1.1 
[28] tibble_3.1.2     
```

**Comment by wlandau** [comment]
I suggest `iteration = "list"` for the `graphs` target.

``` r
library(targets)
  
tar_script({
  library(igraph)
  
  list(
    tar_target(
      matrices,
      list(
        matrix(sample(0:1, 100, replace = TRUE, prob=c(0.9, 0.1)), nc = 10),
        matrix(sample(0:1, 100, replace = TRUE, prob=c(0.75, 0.1)), nc = 10)
      ),
      iteration = 'list'
    ),
    tar_target(
      graphs,
      graph_from_adjacency_matrix(matrices),
      map(matrices),
      iteration = "list"
    )
  )
})

tar_make()
#> 
#> Attaching package: ‘igraph’
#> 
#> The following objects are masked from ‘package:stats’:
#> 
#>     decompose, spectrum
#> 
#> The following object is masked from ‘package:base’:
#> 
#>     union
#> 
#> • start target matrices
#> • built target matrices
#> • start branch graphs_453e9959
#> • built branch graphs_453e9959
#> • start branch graphs_53a5f423
#> • built branch graphs_53a5f423
#> • built pattern graphs
#> • end pipeline

tar_read(graphs, branches = 1)
#> [[1]]
#> IGRAPH 8864446 D--- 10 9 -- 
#> + edges from 8864446:
#> [1]  1-> 6  2-> 6  3-> 3  4-> 4  4-> 9  5-> 6  7-> 4  8->10 10-> 8
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by robitalec** [comment]
Interesting ok - that makes sense. 
I mistakenly assumed the iteration type just needed to be set original tar_group/iteration="group" target.
Apologies for the mislabel as a bug!

An aside, but is there a disadvantage in terms of efficiency from setting iteration globally in my project to "list"?
