### ISSUE TITLE
Export the Target Markdown engine so {knitr} can register it directly

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#503]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [N/A] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [N/A] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [N/A] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [N/A] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Thanks @yihui for being willing to register the engine from `knitr`!

**Comment by yihui** [comment]
Please feel free to open a PR to **knitr** after the next version of **targets** is on CRAN: https://github.com/yihui/knitr/blob/440d1a694e791f5516500472fe99cad84237eaeb/R/engine.R#L777-L785

Before it is "officially" registered in **knitr**, you can make the transition smoother by testing if `is.null(knitr::knit_engines$get('targets'))` on your side, and register the engine only when it is NULL. Then after the future version of **knitr** that officially supports this engine is on CRAN, you can remove the registration on your side.

**Comment by wlandau** [comment]
> Please feel free to open a PR to knitr after the next version of targets is on CRAN: https://github.com/yihui/knitr/blob/440d1a694e791f5516500472fe99cad84237eaeb/R/engine.R#L777-L785

That's very generous of you, Yihui! I plan to update `targets` on CRAN on July 21, and I will definitely submit a PR to `knitr` soon after. Looks straightforward to implement on my end. 

> Before it is "officially" registered in knitr, you can make the transition smoother by testing if is.null(knitr::knit_engines$get('targets')) on your side, and register the engine only when it is NULL. Then after the future version of knitr that officially supports this engine is on CRAN, you can remove the registration on your side.

Good point, implemented in https://github.com/ropensci/targets/commit/d10358118138bce4031580d5d913264e8b641036. Companies in my industry are usually slow to catch up with CRAN, so I may wait a few more months before removing the engine registration from `.onLoad()` in `targets`.

> BTW, you have zero open issues in this repo? Seriously? That's amazing. I feel jealousy.

Thanks! Definitely feels good to be reasonably caught up. Really enjoying GitHub Discussions for the more fluid threads.

**Comment by yihui** [comment]
Sounds great!
