### ISSUE TITLE
On error occured, why not wait for unfinished targets to finish.

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#534]
### Discussed in https://github.com/ropensci/targets/discussions/533

<div type='discussions-op-text'>

<sup>Originally posted by **xinstein** June 28, 2021</sup>
I am running into a problem which prevents me from using targets effectively:
I have a big graph and I run it in parallel using tar_make_future,
when one of the targets encountered error, there's a good chance that there are multiple parallel targets which are nearly finished, I think it would be more economical if we let them finish than make them stop immediately and start over on next make.

Currently there are three options to error handling: "stop"/"workspace"/"continue":
"stop"/"workspace" : These options will cause the concurrent jobs to stop immediately and completely start over on next launch, just as I described;
"continue": This will simply skip any failed targets and launch downstream jobs. I can't think of any good use case for this option.</div>

**Comment by wlandau** [comment]
@xinstein, https://github.com/ropensci/targets/pull/535 implements `tar_target(error = "abridge")` which does what you describe. `error = "stop"` is still the default because it is usually preferable. In a large fraction of cases, if one target fails, then similar targets are also likely to fail. It is usually best to stop and debug early to avoid wasting computing resources.

**Comment by xinstein** [comment]
> @xinstein, #535 implements `tar_target(error = "abridge")` which does what you describe. `error = "stop"` is still the default because it is usually preferable. In a large fraction of cases, if one target fails, then similar targets are also likely to fail. It is usually best to stop and debug early to avoid wasting computing resources.

Thank you very much, that's an unexpectedly quick response!

I agree with what you said about "stop" being preferable, but only for some projects. In my case I have a large project with large branches which share no code in common and has little correlation until very late stage. My case shouldn't be very uncommon among data analysts, to my knowledge.

I'll try it out as soon as possible.
