### ISSUE TITLE
Support the `eval` chunk option

### ISSUE THREAD

**Issue by fkohrt** [ropensci/targets#552]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Support the [`eval` chunk option](https://yihui.org/knitr/options/#code-evaluation) so that targets can be defined conditionally. Example: The following document should never print "Do not print this."

``````Rmd
---
title: "Demo"
output: html_document
---
```{r}
library(targets)
```

```{targets never_run, tar_simple = TRUE, eval = FALSE}
print("Do not print this.")
```

```{r}
tar_make()
```
``````

My usecase are targets depending on the output format:

``````Rmd
---
title: "Conditional evaluation"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(targets)
```

```{targets some-latex-targets, eval = knitr:::is_latex_output()}
list(
  tar_target(
    ...
  )
)
```

```{targets some-html-targets, eval = knitr:::is_html_output()}
list(
  tar_target(
    ...
  )
)
```
``````

**Comment by wlandau** [comment]
Sure, that sounds reasonable. Should work now, but there is a catch: in non-interactive mode, a `{targets, eval = TRUE}` chunk writes a script to `_targets_r/` to register the target(s). If you switch to `eval = FALSE`, the old script will still be there. So I recommend running `tar_unscript()` near the top of the report in order to remove old targets. The example reports in the documentation do this.

**Comment by fkohrt** [comment]
Awesome, thanks for the quick response!
