### ISSUE TITLE
Vector iteration in dynamic branching not aggregating as expected?

### ISSUE THREAD

**Issue by MilesMcBain** [ropensci/targets#560]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Based on the description of vector iteration for dynamic branching, I would have thought that dynamic targets that return vectors would get combined with `vctrs::vec_c` and then split in subsequent downstream dynamic iterations with `vctrs::vec_slice`.

Something confusing is happening, where the aggregated target does seem to have been combined properly, but then downstream targets are iterating over the subsets returned by the individual upstream branches, as if I were using "list" mode iteration.

## Reproducible example

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).
```r
targets::tar_dir({
  targets::tar_script(
    {
      library(targets)
      tar_option_set(error = "workspace")

      list(
        tar_target(
          a_vector,
          c("a", "b", "c")
        ),
        tar_target(
          more_vectors,
          paste0(a_vector, c("1", "2", "3")),
          pattern = map(a_vector)
        ),
        tar_target(
          still_more_vectors,
          if (!rlang::is_string(more_vectors)) stop("shouldn't I have got a string?, got: ", paste0(more_vectors, collapse = " ")),
          pattern = map(more_vectors)
        )
      )
    },
    ask = FALSE
  )
  targets::tar_make()
})
#> • start target a_vector
#> • built target a_vector
#> • start branch more_vectors_210325d0
#> • built branch more_vectors_210325d0
#> • start branch more_vectors_6e5b88fc
#> • built branch more_vectors_6e5b88fc
#> • start branch more_vectors_48e6f6bf
#> • built branch more_vectors_48e6f6bf
#> • built pattern more_vectors
#> • start branch still_more_vectors_67c2c951
#> ✖ error branch still_more_vectors_67c2c951
#> • record workspace still_more_vectors_67c2c951
#> • end pipeline
#> Error : shouldn't I have got a string?, got: a1 a2 a3
#> Error: callr subprocess failed: shouldn't I have got a string?, got: a1 a2 a3
#> Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
```

## Expected result

The pipeline does not error, and `tar_read(still_more_vectors)` returns a single vector of all `TRUE`, of length 9.

## Diagnostic information

```
sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] conflicted_1.0.4  dotenv_1.0.3      targets_0.4.2     tarchetypes_0.2.1
[5] rlang_0.4.11     

loaded via a namespace (and not attached):
 [1] highr_0.9          pillar_1.6.1       compiler_4.1.0     R.methodsS3_1.8.1 
 [5] R.utils_2.10.1     remotes_2.4.0      tools_4.1.0        digest_0.6.27     
 [9] evaluate_0.14      jsonlite_1.7.2     grkstyle_0.0.3     lifecycle_1.0.0   
[13] tibble_3.1.2       R.cache_0.15.0     pkgconfig_2.0.3    reprex_2.0.0      
[17] igraph_1.2.6       rstudioapi_0.13    cli_3.0.1          curl_4.3.2        
[21] yaml_2.2.1         xfun_0.24          fastmap_1.1.0      knitr_1.33        
[25] withr_2.4.2        styler_1.5.1       fs_1.5.0           vctrs_0.3.8       
[29] tidyselect_1.1.1   glue_1.4.2         data.table_1.14.0  R6_2.5.0          
[33] processx_3.5.2     fansi_0.5.0        rmarkdown_2.9      clipr_0.7.1       
[37] purrr_0.3.4        callr_3.7.0        magrittr_2.0.1     rematch2_2.1.2    
[41] htmltools_0.5.1.1  backports_1.2.1    ps_1.6.0           codetools_0.2-16  
[45] ellipsis_0.3.2     mmstyle_0.0.0.9000 utf8_1.2.1         cachem_1.0.5      
[49] crayon_1.4.1       R.oo_1.24.0 
```
I have also observed the same result on the current `HEAD` of the source on this repo.

**Comment by wlandau** [comment]
This behavior is by design. If you map over a dynamic target, the computation happens on each upstream branch, not the elements of the aggregated vector. The `iteration` setting governs what happens when you:

1. Branch over a non-dynamic target, and 
2. Aggregate a dynamic target.

This is what I mean at https://books.ropensci.org/targets/dynamic.html#iteration when I say:

> The iteration arguments of tar_target() and tar_option_set() control the slicing of stems and the aggregation of patterns.

To map over the underlying vector elements instead of branches, you can add an intermediate target that triggers aggregation:

```r
# _targets.R
library(targets)
list(
  tar_target(
    a_vector,
    c("a", "b", "c")
  ),
  tar_target(
    more_vectors,
    paste0(a_vector, c("1", "2", "3")),
    pattern = map(a_vector)
  ),
  tar_target(
    aggregated,
    more_vectors
  ),
  tar_target(
    still_more_vectors,
    aggregated,
    pattern = map(aggregated)
  )
)
```
