### ISSUE TITLE
Add chdir option to tar_make

### ISSUE THREAD

**Issue by atusy** [ropensci/targets#566]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

I suggest adding `chdir` option to `tar_make` like `source`, which if `TRUE` changes working directory to the place where the script exists, and reset the working directory with `on.exit`.

### Background

Currently `tar_make` fails if

- trying to `tar_make` on a script in subdirectories (e.g., `foo/_targets.R`)
- and the script tries to open a file with a path relative to the script

A workaround is to `setwd` prior to `tar_make`, however, chaning working directory on user side may often cause troubles.

- user may forget to reset working directory
- even if user tries reset, reset may not be invoked when `tar_make` stops with an error.

Please describe the new feature. If applicable, write a minimal example in R code or pseudo-code to show input, usage, and desired output.

**Comment by wlandau** [comment]
Temporarily changing the directory is straightforward using `withr::with_dir()`. You can also now set the path to `_targets.R` and `_targets` using arguments to `tar_config_set()`. It works by modifying a `_targets.yaml` configuration file in the current working directory.

**Comment by atusy** [comment]
got it. thank you

**Comment by wlandau** [comment]
The new multi-project config functionality might also come in handy, depending on what you are doing: https://books.ropensci.org/targets/projects.html#multiple-projects

**Comment by atusy** [comment]
Interesting! Thank you for letting me know!!
