### ISSUE TITLE
Support URL resources without ETag or Last-Modified

### ISSUE THREAD

**Issue by atusy** [ropensci/targets#576]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Currently, `tar_target(format = "url")` raises error if the URL misses ETag or Last-Modified (see reprex below).

I would suggest simply set maximum cache age to 0, and always re-download the resource.

Note that this is the strategy of https://github.com/rstudio/pins .

1. For the first time, try get `max-age` from [Cache-Control](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Cache-Control), falling back to `NULL` at https://github.com/rstudio/pins/blob/322b3df464202ef3a4726cded3f1a549cefef11c/R/legacy_pin_download.R#L113
2. If the old cache exists, retrieve `max-age`, falling back to 0 at https://github.com/rstudio/pins/blob/322b3df464202ef3a4726cded3f1a549cefef11c/R/legacy_pin_download.R#L92
3. Check if max-age still valid at https://github.com/rstudio/pins/blob/322b3df464202ef3a4726cded3f1a549cefef11c/R/legacy_pin_download.R#L103

### Reprex

``` r
targets::tar_dir({
  targets::tar_script(
    targets::tar_target(url, "https://gihyo.jp/book/list", format="url")
  )
  targets::tar_make()
})
#> • start target url
#> • end pipeline
#> Error : no ETag or Last-Modified for url: https://gihyo.jp/book/list
#> Error: callr subprocess failed: no ETag or Last-Modified for url: https://gihyo.jp/book/list
#> Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
```

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
`targets` needs trustworthy validators to check if a target is up to date or if it needs to rerun. If no validators exist, `targets` cannot do its job of deciding whether to rerun the target, and a non-URL format would be more appropriate. HTTP caching does not seem like a good fit because the goals are different (a target does not expire unless you explicitly request it with something like `tar_age()`)  and the mechanism seems system-dependent, configuration-dependent, and potentially brittle.

**Comment by atusy** [comment]
Thanks for the reply. I understand. 
In that case, I think the error message is not kind enough since the visit to https://books.ropensci.org/targets/debugging.html will not help.
I think error message should suggest a non-URL format as you do in the reply.

**Comment by wlandau** [comment]
That's fair, please see 47b50bb2f5af91fbf29838099040042c35cdc9e5.

**Comment by atusy** [comment]
Great!! Thank you so much!!!
