### ISSUE TITLE
tar_ignore()

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#61]
Could require custom code analysis, or we might be able to solve it with text processing.

**Comment by kendonB** [comment]
This was a feature of `drake` I quite liked and would be a big loss. There are so many objects out there that store irrelevant things like timestamps that can be safely ignored. Some things are expensive to hash so you'd like to just ignore them, especially when building a workflow.

Do you have plans to develop these "alternative DSLs"? Not quite sure if you mean a package that depends on `targets` or a separate one with different internals like `drake`.

There might be reasonable workarounds I haven't thought about as well. My immediate example is a scraper that depends on a `polite::bow` session which has a different hash every time it runs. Maybe isolating it and playing with triggers will work. I'll have a try.

**Comment by wlandau** [comment]
I hear you, but the cost of `tar_ignore()` would simply be too high. To increase performance and decrease confusion, `targets`` uses as little static code analysis as possible, relying completely on `codetools::findGlobals()` for all of it. As soon as we need to search statically for `ignore()`, we either need to run our own static code analysis routine alongside `codetools`, which is slow, or independently replicate `codetools` in a custom static code analysis routine, which is what `drake` did. Either option would be a large implementation and maintenance burden, and because of all the things I learned from how `codetools` works internally, the latter option would force us to change the license of `targets` from MIT to GPL-3.

I now actually don't think we need alternative DSLs and I do not plan to write one. The metaprogramming possibilities at https://wlandau.github.io/targets-manual/branching.html#metaprogramming mean we do not need to implement anything special for static branching.

If you simply want to ignore a dependency, `eval(quote())` fools `codetools` into ignoring objects.

```{r}
> codetools::findGlobals(function() x)
[1] "x"
> codetools::findGlobals(function() evalq(x))
[1] "evalq" "x"    
> codetools::findGlobals(function() eval(quote(x)))
[1] "eval"  "quote"
```

If you do not want such a change to activate the command cue (see `?tar_cue`) then you could always supply your original command to `tar_target_raw()`, and set the `deps` and `string` arguments manually.

**Comment by wlandau** [comment]
Just added some guidance at https://wlandau.github.io/targets-manual/practice.html#dependencies.
