### ISSUE TITLE
let `tar_prune()` returns some message about what have been pruned

### ISSUE THREAD

**Issue by yyzeng** [ropensci/targets#617]
I use `tar_prune()` to remove targets that are no longer part of the pipeline (which are built during my trial and error). But `tar_prune()` tells us nothing about what have been pruned. Will it be better to feedback some message by setting an option like `verbose = TRUE` (sometimes just for coder's curiosity) ? Thanks.

**Comment by wlandau** [comment]
Such a message would g

**Comment by wlandau** [comment]
Such a message could get really long, I don’t think it would be reliable for what you want. Instead, I recommend comparing the output of tar_meta() or tar_objects() to the output of tar_manifest() before you run tar_prune(). That will give you an idea of which targets will be pruned.

**Comment by yyzeng** [comment]
Got it! Thank you!

**Comment by andtheWings** [comment]
For what it's worth, I also wish this were a feature. Perhaps by default it could truncate the output if there are concerns about the message being too long, Also, perhaps the default could be verbose=FALSE, but verbose=TRUE could give the output some users want?
