### ISSUE TITLE
`partial` blocks dependency discovery

### ISSUE THREAD

**Issue by xinstein** [ropensci/targets#638]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description
purrr::partial is not compatible with dependency discovery

## Reproducible example

```
funb = function(aux.arg)print(aux.arg)

funa = funb %>% partial(aux.arg = 1)

list(tar_target(tarname, funa()))
```
funb is not discovered as a dependency of funa, and thus any change to funb will not trigger a rerun

* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

funb is not discovered as a dependency of funa, and thus any change to funb will not trigger a rerun

## Diagnostic information

* A [reproducible example](https://github.com/tidyverse/reprex).
* Session info, available through `sessionInfo()` or [`reprex(si = TRUE)`](https://github.com/tidyverse/reprex).
* A stack trace from `traceback()` or `rlang::trace_back()`.
* The [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the GitHub commit of `targets` currently installed. `packageDescription("targets")$GithubSHA1` shows you this.

**Comment by mattwarkentin** [comment]
Hi @xinstein,

I think this is an issue with the pipe (`%>%`) and `partial()`. Check out this reproducible example:
``` r
library(purrr)
library(globals)

funb = function(aux.arg) print(aux.arg)

funa_1 = funb %>% partial(aux.arg = 1)
funa_1
#> <partialised>
#> function (...) 
#> .(aux.arg = 1, ...)

funa_2 = partial(funb, aux.arg = 1)
funa_2
#> <partialised>
#> function (...) 
#> funb(aux.arg = 1, ...)

findGlobals(funa_1)
#>  [1] "{"           "env_bind"    "mask"        "env_get"     "current_env"
#>  [6] "eval_tidy"   "call"        "~"           "print"       "."
findGlobals(funa_2)
#>  [1] "{"           "env_bind"    "mask"        "env_get"     "current_env"
#>  [6] "eval_tidy"   "call"        "~"           "print"       "funb"
```

Note the function signatures produced by `partial()`. The piped version returns a function that calls `.`, whereas the second version properly calls `funb()`. As a consequence, in the piped version of `funa_1`, it detects the global `.`. This is because in piped calls, the LHS is piped into the RHS as `.`. In the second example, `funa_2` detects all of the proper globals including `funb`.

I don't think this is a `targets` issue. Have you tried this with the new base `R` pipe? It builds the function calls on the `R` parser side, and so it might not suffer from the same issue as the `magrittr` pipe, but I don't now for sure.

**Comment by xinstein** [comment]
Thank you! I was unaware of the new built-in pipe! That solved the original problem.

But I noticed a new problem: a change of the argument value , i.e. `aux.arg = 1` to `aux.arg = 2`, does not trigger a re-run either.

```
funb = function(aux.arg)print(aux.arg)

#funa = funb |> partial(aux.arg = 1)
funa = funb |> partial(aux.arg = 2)

list(tar_target(tarname, funa()))
```

**Comment by xinstein** [comment]
That might be a problem of the `partial` function.

But how should users know what kinds of functions have similar problems and how to avoid them.

Maybe a piece of documentation (and I believe it deserves special notice) might help a lot

**Comment by mattwarkentin** [comment]
Could you please provide a minimal reproducible example? I was not able to reproduce your issue with the following code:
```r
library(targets)
library(purrr)

funb <- function(aux.arg) print(aux.arg)

list(
  tar_target(
    funa,
    partial(funb, aux.arg = 1)
  )
)
```
```
tar_make()
```
```
• start target funa
• built target funa
• end pipeline
```
```
tar_read(funa)
```
```
<partialised>
function (...) 
funb(aux.arg = 1, ...)
```

## Change to `aux.arg ` = 2
```r
library(targets)
library(purrr)

funb <- function(aux.arg) print(aux.arg)

list(
  tar_target(
    funa,
    partial(funb, aux.arg = 2)
  )
)
```
```
tar_make()
```
```
• start target funa
• built target funa
• end pipeline
```
tar_read(funa)
```
```
<partialised>
function (...) 
funb(aux.arg = 2, ...)
```
```

**Comment by MilesMcBain** [comment]
Here's a reprex for this issue:

``` r
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
Sys.setenv("TAR_ASK" = "false")
targets::tar_script({
  library(purrr)
  funb <- function(aux.arg) aux.arg
  funa <- partial(funb, aux.arg = 1)
  list(
      targets::tar_target(
          tar_name, funa()
      )
    )
})
targets::tar_make()
targets::tar_script({
  funb <- function(aux.arg) aux.arg
  library(purrr)
  funa <- partial(funb, aux.arg = 2)
  list(
      targets::tar_target(
          tar_name, funa()
      )
    )
})
targets::tar_make()
})
#> * start target tar_name
#> * built target tar_name
#> * end pipeline
#> v skip target tar_name
#> v skip pipeline
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

One thing I noticed is that if you use an anonymous function instead of `partial` everything works as expected:

``` r
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
Sys.setenv("TAR_ASK" = "false")
targets::tar_script({
  library(purrr)
  funb <- function(aux.arg) aux.arg
  funa <- function() funb(aux.arg = 1)
  list(
      targets::tar_target(
          tar_name, funa()
      )
    )
})
targets::tar_make()
targets::tar_script({
  funb <- function(aux.arg) aux.arg
  library(purrr)
  funa <- function() funb(aux.arg = 2)
  list(
      targets::tar_target(
          tar_name, funa()
      )
    )
})
targets::tar_make()
})
#> * start target tar_name
#> * built target tar_name
#> * end pipeline
#> * start target tar_name
#> * built target tar_name
#> * end pipeline
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MilesMcBain** [comment]
This might give some insight as to why `partial` is failing:

``` r
library(purrr)
funb <- function(aux.arg) aux.arg
funa <- partial(funb, aux.arg = 1)
func <- partial(funb, aux.arg = 2)
class(funa)
#> [1] "purrr_function_partial" "function"
args(funa)
#> function (...) 
#> NULL
body(funa)
#> {
#>     env_bind(mask, ... = env_get(current_env(), "..."))
#>     eval_tidy(call, mask)
#> }
class(func)
#> [1] "purrr_function_partial" "function"
args(func)
#> function (...) 
#> NULL
body(func)
#> {
#>     env_bind(mask, ... = env_get(current_env(), "..."))
#>     eval_tidy(call, mask)
#> }
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I don't know for sure, but I'd expect targets to have special handling for objects your plan depends on of class `function`, and that involves comparing their args and body which are identical in this case.

**Comment by mattwarkentin** [comment]
I thought functions/code were compared by hashing (after removing superfluous whitespace, but this would likely pick up the differences in arguments.
``` r
library(purrr)
library(digest)
funb <- function(aux.arg) aux.arg
funa <- partial(funb, aux.arg = 1)
func <- partial(funb, aux.arg = 2)

digest(funa)
#> [1] "58d3ed51ef051355fc6699a8eb355aa8"
digest(func)
#> [1] "4687277556f28d79394db8f1839de4b9"
```

**Comment by wlandau** [comment]
Thanks everyone for the discussion.

This edge case comes up regularly, and it is not unique to `partial`. Other examples include `base::Vectorize()` and `purrr::safely()`. The actual function gets moved to the  function's closure (environment) where `targets` does not know where to find it.

I recommend checking `tar_visnetwork()` and/or `tar_deps()` before you run the project. If a function is missing or the dependency graph is incorrectly disconnected in some way, you will be able to see that before you run the pipeline. Mentions/discussions are in https://books.ropensci.org/targets/walkthrough.html#inspect-the-pipeline and https://books.ropensci.org/targets/targets.html#dependencies.

A bit more context:`targets` takes the hash of the deparsed function body and arguments.

https://github.com/ropensci/targets/blob/d972f61d67028d2db795c9d72f6c3e18e7cabef2/R/utils_imports.R#L75-L81

It is important that we hash the deparsed text, not the function itself. In the latter case, we would end up with https://github.com/ropensci/drake/issues/345.

**Comment by xinstein** [comment]
Thank you , very helpful discussion, had a lot of "fun".

So global objects only have their arguments and bodies monitored and parsed, but not the function environment, I think I got it! That might save me tons of debugging time in the future.
