### ISSUE TITLE
Unable to link targets if name starts with `.`

### ISSUE THREAD

**Issue by dipterix** [ropensci/targets#662]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/). 

## Description

If the name is irregular, then `targets` cannot link them correctly

## Reproducible example

This is my `_targets.R`, no other files

```r
require(targets)

list(
  tar_target(
    ...var1,
    {
      123
    }
  ),
  tar_target(
    ...var2,
    {
      ...var1 + 1
    }
  )
)
```

<img width="665" alt="image" src="https://user-images.githubusercontent.com/8163576/137597427-5867698a-4e8f-4b3e-8b15-521ecea0b3a5.png">

## Expected result

`...var2` should depend on `...va1`

## Diagnostic information

`targets 0.8.0`

I'm not sure, but I suspect this line could be it?

https://github.com/ropensci/targets/blob/200697ca77791d19ba71d5626bed620c0965d312/R/class_settings.R#L128

`ls(all.names=FALSE)` will remove `...var1` since R thinks it's hidden.

**Comment by wlandau** [comment]
Unfortunately I cannot make `..name` targets work because of how environments work in R. `lapply(env, ...)` automatically drops elements whose names begin with dots, and the workarounds I can think of are not performant enough. But I did just make `tar_target()` throw an informative error when the user defines such a target.

**Comment by dipterix** [comment]
Why using `lapply(env, ...)` ? You can use `lapply(as.list(env), ...)` which won't add any performance burden. 

In fact, using `ls()` itself is inefficient if the pipeline scale is large. `names(as.list(env))` is faster.

**Comment by wlandau** [comment]
Those functions are internal (see below). Do you really need targets with leading dots?  Seems easy to avoid this edge case, especially with the new informative error.

https://github.com/ropensci/targets/blob/1b02aebcda340d84d20c5d716a045551e7596f75/R/utils_functional.R#L1-L19

**Comment by wlandau** [comment]
> our goal is to let users write error-free pipelines without reading more than one page of documentation.

If that can be done, it would add a lot to this ecosystem. So far, my own attempts at this have been through [targetopia packages](https://wlandau.github.io/targetopia/) that abstract away the details of pipeline construction, particularly with [dynamic branching](https://books.ropensci.org/targets/dynamic.html), which otherwise usually requires a serious read and some practice for most people.

**Comment by dipterix** [comment]
Yes, if you apply for grants nowadays in the universities, they really want you to focus on reproducibility (one of the key points). So making sophisticated pipeline frameworks is very important. But since there are so many pipeline tools. To attract users, we want to make the packages robust and really easy to use. That means no errors when using the default settings, otherwise we are passing the responsibilities to the users to fix the bug they "should've" known. It's sad because users should always read the user-manual, but nobody wants to do so. 

Personally I really like `targets`, so I spent time to read your source code trying to break your package : D

**Comment by steveb-123** [comment]
I just came upon something related to this with targets equivalent to the below:

```.R
tar_target(named_vector, c("a", "b") %>% set_names(c("first", "second"))),
tar_target(recoded_factor, recode(factor(c("first", "second")), !!!named_vector))
```

Where the `tar_manifest()` failed  because `enexpr(expr) : object 'named_vector' not found`. 

There is a another bug report here (I think) mentioning this and you, @wlandau, mentioned that you expanded the error message to help out here (if I understood correctly). This is just a note to say that I didn't get anything useful in my error. It took a little while to work out the `!!!` was the culprit. I have now buried the spicing operator in a separate function and things are rolling again, but a specific error message or google-able documentation entry would help a lot. 

Adding that above two lines to a functioning `_targets.R` should reproduce.
I can write a complete BR if that is useful.

I tried `tidyverse` and `rlang` in `tar_option_set` `packages`, and I'm running `targets_0.13.1.900`.

**Comment by wlandau** [comment]
See the `tidy_eval` argument of `tar_target()` and `tar_option_set()`. `!!` and `!!!` act when the target is defined, inserting objects you define elsewhere in `_targets.R`. If you don't want `!!` or `!!!` to run until `tar_make()`, set `tidy_eval = FALSE`.

**Comment by dipterix** [comment]
@steveb-123 I'm not the author of this package so I can't say this for sure, but I guess what you have encountered was an expected behavior. 

## Detailed explanation

When `targets` runs your code, there are two phases: compile and make. 

* During the compiling phase, `tar_target` analyzes your expressions, trying to find variables that match the target names and plan the order of executing your code. To accomplish this goal, `targets` needs to "quote" the expression (in this case, `recode(factor(c("first", "second")), !!!named_vector)`) without evaluating the expression. 
* During the making phase, `tar_make` execute the script (targets) in an order determined in the previous phase

When compiling the pipeline, `targets` uses a package called `rlang` to help expand the expression instead of native R `substitute` or `bquote`. Although two approaches are very similar, both provide special types of quote called "quasi-quosure", enabled by `!!` or `!!!`. The quasi-quosures will be substituted by values of existing variables when quoted, just like `.(...)` in `bquote`. 

Since there are two phases, it's very important to understand when the quasi-quosures are expanded/substituted.  By default `targets` expand `!!` or `!!!` when compiling the pipeline. This means it expects variable `named_vector` to exist when running those `tar_target(...)` calls. However, it can't. This is because the variable `named_vector` is only generated when making the pipeline (during `tar_make`). Since the variable isn't available, it complains that `named_vector` is not found.

## What might be the solution

From what I understand, you were trying to let the second target run `recode(..., named_vector)`, where `named_vector` is generated from the previous target. If this is the case, then you don't need `!!!`. Simply

```r
tar_target(named_vector, c("a", "b") %>% set_names(c("first", "second"))),
tar_target(recoded_factor, recode(factor(c("first", "second")), named_vector))
```

Why this is the case:

Remember `targets` automatically parses your code and resolves dependence? During the first compiling phase, when it analyze your code `recode(factor(c("first", "second")), named_vector)`, it will be aware that variable `named_vector` hasn't been defined in this code block, so it will try to look for target with this name, and automatically link to the previous target.

## Suggestions

Quasi-quosures `!!` and `!!!` might bring you a little bit convenience while using tidyverse packages, since you can pipe-up your function calls without stopping. However, I strongly discourage you to using them in other scenarios. This is not saying you shouldn't use `rlang` syntax. It just require you to know very well how R code are executed, and you have to be boring enough (like me) to read some other packages' source code. Also, `rlang` is not a base package, your code might break if Hadley decides to change the core behaviors to be in favor of their own products some day. I wrote a package 4 years ago. That package depend heavily on rlang, and I have to bare the pain every time they (rlang package) make big changes.

**Comment by steveb-123** [comment]
@wlandau D'oh. Apologies, I should have seen that. Thanks for the quick response. Setting `tidy_eval = FALSE` allowed me to revert back to that which I originally tried, with success.

@dipterix Thanks for your feedback. In my use case I need the `!!!` splicing to expose the (very long in the original script) named list as `...` items for `recode`.
