### ISSUE TITLE
Native versioning support for AWS targets

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#711]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Background

This issue ~~replaces~~ is an alternative to https://github.com/wlandau/gittargets/issues/6. When completed, [`gittargets`](https://github.com/wlandau/gittargets) will automatically be cloud-enabled with no loss of performance.

Cross-referencing https://github.com/ropensci/software-review/issues/486.

## Proposal

* For targets with `tar_target(..., format = "aws_parquet")` or similar AWS format, store the AWS S3 object version ID if versioning is enabled in the bucket.
* In `tar_read()` and similar, read the object with the version ID in the metadata.

That way, when `gittargets::tar_git_checkout()` reverts the metadata, `targets` will automatically use the prior version of the object everywhere.

**Comment by wlandau** [comment]
As part of this issue, I need to back-compatibly change the format of the AWS path, probably to a single character string with all the required key-value pairs. I may also switch from `aws.s3` to `paws` so I can get the version ID from `put_object()`, thus avoiding an extra API call (`head_object()`). For that, I will need to borrow https://github.com/paws-r/paws/blob/main/examples/s3_multipart_upload.R.

**Comment by wlandau** [comment]
Should probably re-enable tracking of _targets/meta/meta in _targets/.gitignore

**Comment by wlandau** [comment]
Did some prework:

* Back-compatibly refactor AWS paths to be arbitrary character vectors of key-value pairs.
* Separate out and test AWS S3 utilities in `R/utils_aws.R`. (This will make it easier to switch to `paws`, but that's a serious refactor I am not sure is necessary.)
* Add and test the ability to get AWS object versions through the `aws_version()` utility.

Next steps:

* Modify `R/utils_aws.R` functions to optionally accept a version string.
* Write tests that versions are truly optional.
* Write tests that versions retrieve the appropriate objects.
* Use versions in AWS targets.
* Test that versions are used correctly in AWS targets.

**Comment by wlandau-lilly** [comment]
Switched to paws after all. Easier to deal with versions that way. Next steps are testing:

* [ ] Adapt everything in `tests/aws/` to use paws and work again.
* [ ] Double-check aws.s3 is totally gone.
* [ ] Fill in test specs at the bottom of `tests/aws/test-utils_aws.R`.
* [ ] Add versioning single-part tests in a pipeline.
* [ ] Same with multipart.

**Comment by wlandau** [comment]
Done!
