### ISSUE TITLE
list iteration slicing like vector, not list

### ISSUE THREAD

**Issue by mkoohafkan** [ropensci/targets#712]
Consider the following reprex

```r
# _targets.r

library(targets)

make_list = function() {
  list(mtcars[1:2,], mtcars[3:4,], mtcars[5:6,])
}


is_dataframe = function(x) {
  class(x)
}

list(
  tar_target(a, make_list()),
  tar_target(b, is_dataframe(a), pattern = map(a), iteration = "list")
)

```

And in the console:

```r
targets::tar_make()

targets::tar_read(b)
## $b_2576385c
## [1] "list"
## 
## $b_d82f2f18
## [1] "list"
## 
## $b_be761317
## [1] "list"
```

The [documentation](https://books.ropensci.org/targets/dynamic.html#list-iteration) states that list iteration should slice like `[[`, but it seems that it is slicing like `[` instead, resulting in the type of each branch being `list` rather than `data.frame`.

**Comment by mkoohafkan** [comment]
I figured out the issue, the critical distinction here is that the target *creating* the list must also have the argument `iteration = "list"`:

```r
#_targets.r

library(targets)

make_list = function() {
  list(mtcars[1:2,], mtcars[3:4,], mtcars[5:6,])
}


is_dataframe = function(x) {
  class(x)
}

list(
  tar_target(a, make_list(), iteration = "list"), # no pattern but still needs argument 'iteration'!
  tar_target(b, is_dataframe(a), pattern = map(a), iteration = "list")
)
```

Might be helpful to emphasize this in the documentation, especially since vector iteration doesn't require the iteration to be specified in the first target. I read the docs multiple times and still missed this.

**Comment by wlandau** [comment]
I feel this is covered earlier on, in the first paragraph of the section on iteration:

> The iteration arguments of tar_target() and tar_option_set() control the slicing of stems and the aggregation of patterns. For example, if you write a stem target with tar_target(x, fun(), iteration = "list"), then all downstream targets that branch over x will give list-like slices x[[1]], x[[2]], etc.

In your case, `a` is the stem and `b` is the pattern.

**Comment by mkoohafkan** [comment]
That's true, but the immediate example that follows is vector iteration that does not require any `iteration` specification, and all of the preceding examples in the chapter use the default vector behavior and thus do not specify `iteration` in the stems. I personally found the documentation on list iteration---and specifically on specifying `iteration` in the stem---confusing, and a couple of minor changes could save new users a lot of time. I suggest a bit of additional emphasis on specifying `iteration` in the stem in section 11.9.2, or maybe just change the vector iteration examples in section 11.9.1 to explicitly pass `iteration = "vector"` (even though this is the default value) as an additional cue to readers that the stem needs an iteration specification.

**Comment by wlandau** [comment]
Fair enough, I added some more commentary in https://github.com/ropensci-books/targets/commit/bc3b134c22772ccf2789bad58ccb866206f56c38.
