### ISSUE TITLE
target always gets made when including Rcpp function

### ISSUE THREAD

**Issue by matthiaskaeding** [ropensci/targets#721]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Using [`targets::tar_reprex()`](https://docs.ropensci.org/targets/reference/tar_reprex.html), [`reprex::reprex()`](https://reprex.tidyverse.org/reference/reprex.html), or similar, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Hi, thanks for all the work, this is a really great package and I use it a lot.
 
The problem: If a target depends on a  Rcpp function it always reruns. This is basically the same bug as [this one](https://github.com/ropensci/drake/issues/806) for drake. 

## Reproducible example
```{r}
# targets script
library(targets)
library(Rcpp)
f <- Rcpp::cppFunction(
  "int add(int x, int y, int z) {
      int sum = x + y + z;
      return sum;
    }"
)
list(
  tar_target(x, f(1, 2, 3))
)
```

## Expected result

If one runs targets::tar_make() with the above _targets script, the target 'x' always gets made.

## Diagnostic information

Session info:

R version 4.1.0 (2021-05-18)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 12.0.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_1.0.7    targets_0.9.0 mt_0.0.0.9004

loaded via a namespace (and not attached):
 [1] highr_0.9         pillar_1.6.1      compiler_4.1.0    R.methodsS3_1.8.1 R.utils_2.10.1    tools_4.1.0       digest_0.6.27     evaluate_0.14     jsonlite_1.7.2    lifecycle_1.0.0   tibble_3.1.2     
[12] R.cache_0.15.0    pkgconfig_2.0.3   rlang_0.4.11      reprex_2.0.0      igraph_1.2.8      rstudioapi_0.13   cli_3.0.0         yaml_2.2.1        xfun_0.24         withr_2.4.2       styler_1.6.2     
[23] knitr_1.36        vctrs_0.3.8       fs_1.5.0          tidyselect_1.1.1  glue_1.4.2        data.table_1.14.3 R6_2.5.0          processx_3.5.2    fansi_0.5.0       rmarkdown_2.9     clipr_0.7.1      
[34] callr_3.7.0       purrr_0.3.4       magrittr_2.0.1    htmltools_0.5.1.1 backports_1.2.1   codetools_0.2-18  ps_1.6.0          ellipsis_0.3.2    utf8_1.2.1        crayon_1.4.1      R.oo_1.24.0

**Comment by wlandau** [comment]
Huh, I thought I already took care of that one. Thanks for alerting me. Fixed in e144bdb2a5d7a2c80ae022df434b1354bacf5ad9.

However, the patch is not perfect because now `targets` does not notice any changes to the C++ code. It's an improvement, but still a limitation. So instead of calling `Rcpp::cppFunction()` directly, I recommend using the following wrapper that inserts the text into the function body.

```r
cpp_function <- function(code) {
  out <- Rcpp::cppFunction(code)
  body(out) <- rlang::call2("{", code, body(out))
  out
}

f <- cpp_function(
  "int add(int x, int y, int z) {
     int sum = x + y + z;
     return sum;
   }"
)
```

**Comment by matthiaskaeding** [comment]
That was fast, thanks. I actually simplified my approach for the example, in my original project I have a .cpp file which I source via Rcpp::sourceCpp, I assumed that it makes no difference. With your update, my target now stopped updating, but is there any way for targets to detect changes in the source code for this case? I can upload another example as well.

**Comment by wlandau** [comment]
You can track the C++ file with something like `tar_target(file, "your_file.cpp", format = "file")` and then connect that target as a dependency to anything immediately downstream. Otherwise, `targets`' top priority is R code and does not have automatic support for other languages.

**Comment by alexpghayes** [comment]
Thanks for this fix, it really made my life much nicer!
