### ISSUE TITLE
`targets::tar_visnetwork` zooms too fast

### ISSUE THREAD

**Issue by dipterix** [ropensci/targets#749]
`targets::tar_visnetwork` generates nice htmlwidgets showing the target graphs. However, it zooms in/out too fast. At least on my mac the graph disappears very quickly. Is it possible to apply something like `visNetwork::visInteraction(zoomSpeed = 0.2)` to the widget?

**Comment by wlandau** [comment]
I kept the default zoom speed the same since it works well on most machines, but I did just add a new `zoom_speed` argument to `tar_visnetwork()` and `tar_glimpse()`. Hopefully that helps.

**Comment by dipterix** [comment]
Looks great, thanks :)
