### ISSUE TITLE
re-evaluation of branches without outdated dependencies

### ISSUE THREAD

**Issue by CorradoLanera** [ropensci/targets#767]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Using [`targets::tar_reprex()`](https://docs.ropensci.org/targets/reference/tar_reprex.html), [`reprex::reprex()`](https://reprex.tidyverse.org/reference/reprex.html), or similar, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

In `{targets}` guide ([here](https://books.ropensci.org/targets/dynamic.html#patterns)) there is written:

> A branch is a special kind of target whose dependencies are slices of the targets mentioned in pattern = map(...) etc.

So, if I would like to change only the aggregation of the evaluated branches, their dependencies should not be invalidated, and the branches themself should not be re-evaluated.

In `{targets}` if I change only the aggregation, the dependencies of the branches are not invalidated (as expected), the branches names are not changed (as expected), but `tar_make` re-evaluate them anyway.

## Reproducible example

``` r
library(targets)

tar_dir({
  tar_script(
    {
      library(targets)

      list(
        tar_target(x, 1:2),
        tar_target(y, x, pattern = map(x))
      )
    },
    ask = FALSE
  )
  tar_make()
  str(tar_read(y))

  tar_script(
    {
      library(targets)

      list(
        tar_target(x, 1:2),
        tar_target(y, x, pattern = map(x), iteration = "list")
      )
    },
    ask = FALSE
  )
  tar_make()
  str(tar_read(y))
})
#> * start target x
#> * built target x
#> * start branch y_80b9a5d2
#> * built branch y_80b9a5d2
#> * start branch y_54f0a599
#> * built branch y_54f0a599
#> * built pattern y
#> * end pipeline
#>  Named int [1:2] 1 2
#>  - attr(*, "names")= chr [1:2] "y_80b9a5d2" "y_54f0a599"
#> v skip target x
#> * start branch y_80b9a5d2
#> * built branch y_80b9a5d2
#> * start branch y_54f0a599
#> * built branch y_54f0a599
#> * built pattern y
#> * end pipeline
#> List of 2
#>  $ y_80b9a5d2: int 1
#>  $ y_54f0a599: int 2
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22000)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] targets_0.10.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.1.2    pillar_1.7.0      highr_0.9         tools_4.1.2      
#>  [5] digest_0.6.29     evaluate_0.14     tibble_3.1.6      lifecycle_1.0.1  
#>  [9] pkgconfig_2.0.3   rlang_1.0.1       reprex_2.0.1      igraph_1.2.11    
#> [13] cli_3.1.1         rstudioapi_0.13   yaml_2.2.2        xfun_0.29        
#> [17] fastmap_1.1.0     withr_2.4.3       stringr_1.4.0     knitr_1.37       
#> [21] fs_1.5.2          vctrs_0.3.8       tidyselect_1.1.1  glue_1.6.1       
#> [25] data.table_1.14.2 R6_2.5.1          processx_3.5.2    fansi_1.0.2      
#> [29] base64url_1.4     rmarkdown_2.11    purrr_0.3.4       callr_3.7.0      
#> [33] magrittr_2.0.2    backports_1.4.1   codetools_0.2-18  ps_1.6.0         
#> [37] htmltools_0.5.2   ellipsis_0.3.2    utf8_1.2.2        stringi_1.7.6    
#> [41] crayon_1.4.2
```

</details>

## Expected result

```r
#> * start target x
#> * built target x
#> * start branch y_80b9a5d2
#> * built branch y_80b9a5d2
#> * start branch y_54f0a599
#> * built branch y_54f0a599
#> * built pattern y
#> * end pipeline
#>  Named int [1:2] 1 2
#>  - attr(*, "names")= chr [1:2] "y_80b9a5d2" "y_54f0a599"
#> v skip target x
#> v skip branch y_80b9a5d2
#> v skip branch y_54f0a599
#> * built pattern y
#> * end pipeline
#> List of 2
#>  $ y_80b9a5d2: int 1
#>  $ y_54f0a599: int 2
```

**Comment by wlandau** [comment]
This is a rigid but deliberate behavior to make sure target invalidation rules are applied transparently and consistently regardless of other settings. To ignore changes to the data format for specific targets, you can write `tar_target(..., cue = tar_cue(iteration = FALSE))`.
