### ISSUE TITLE
Respect package:cli environment variable NO_COLOR and option cli.num_colors

### ISSUE THREAD

**Issue by mkoohafkan** [ropensci/targets#770]
Additional context: 
- https://github.com/REditorSupport/vscode-R/issues/942
- https://github.com/r-lib/cli/issues/412

The targets package continues to print ANSI colors even when the environment variable `NO_COLOR` is set or option `cli.num_colors = 1`. This results in ANSI colors getting printed to the screen in vscode-R when the official R terminal is used. See https://cli.r-lib.org/reference/num_ansi_colors.html for more info.

![image](https://user-images.githubusercontent.com/4790348/153095183-ed52dd41-ec1b-46de-994b-653823eda638.png)

**Comment by wlandau** [comment]
This is not a bug, you can disable ANSI colors by setting `options(cli.num_colors = 1)` or `options(crayon.enabled = FALSE)` near the top of your `_targets.R` file. The `tar_make*()` functions do not recognize options set in the main R session because they run the pipeline in a new `callr` session.

**Comment by mkoohafkan** [comment]
Thanks, but I thought by default the `callr` sessions inherited the global environment by default. Wouldn't they inherit the options as well? Or do I misunderstand the documentation for the `envir` argument to `tar_make_*`?

**Comment by wlandau** [comment]
The purpose of the callr session is to discard the current global environment and run the pipeline in a completely fresh, consistent,  reproducible R session. This prevents the pipeline from unpredictable invalidation. As the docs explain, the envir argument of tar_make() is ignored unless callr_function is NULL.

**Comment by mkoohafkan** [comment]
OK thanks, so the `callr` sessions don't pull anything from the *user* `.Rprofile` and `.Renviron` files, nor from `Rprofile.site` and `Renviron.site`. However, it does pull from the *project-specific* `.Rprofile`, but **only if it is in the same directory as `_targets.r`**.

Turns out I have not been using my `renv` environment the whole time, because I have multiple pipelines in one project separated into subdirectories but I run my `renv` commands in the top-level directory (because I want the same `renv` library to be used by every pipeline). I need to add another `.Rprofile` to each subfolder activating the shared `renv` library, or add the logic to the top of each `_targets.r`.

**Comment by mkoohafkan** [comment]
Turns out that's not true, as removing the renv library broke my targets because the packages had not been installed in my default library. How did `targets` in my subdirectories know to use the `renv` library in the top-level directory when there was no `.Rprofile` to point to it? It must have inherited the `renv` library somehow.
