### ISSUE TITLE
The default of `tar_load()` should be `everything()`

### ISSUE THREAD

**Issue by malcolmbarrett** [ropensci/targets#772]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

`tar_load()` by default doesn't have anything set to `name`. In practice, though, I think `tar_load(name = everything())` is a better default. That's almost always what I want when I reach for `tar_load()`.

**Comment by wlandau** [comment]
I do not think this would be wise for medium to large pipelines. Many pipelines have data large enough that `tar_load(everything())` consumes more memory than is on the local machine, and AWS data transfers could be costly in the case of e.g. `tar_option_set(format = "aws_qs")`. if `everything()` were the default, then typos would be dangerous in these situations.

**Comment by malcolmbarrett** [comment]
I see your point about that. Here are a couple of other approaches that might satisfy this workflow without the risk in large pipelines:
* use `menu()` when `names` is null to select targets or `everything()`
* allow for an option to set the default, where I could set `everything()` in my `.Rprofile` or via the targets options structure

It's hard for me to convey just how often I type `tar_load(everything())` 🙃 . I have a wrapper function in my `.Rprofile` now, but my instinct is that this is a very, very common workflow (and likely that most pipelines aren't going to explode when loading everything)

**Comment by wlandau** [comment]
I would put it in the `tar_config_set()` interface, but the non-standard evaluation of that argument would make it brittle and awkward from a UX side.

What about a new `tar_load_all()` function? Interested in writing a PR?

**Comment by malcolmbarrett** [comment]
That sounds reasonable to me. I'll prep something soon
