### ISSUE TITLE
Minor doc issue: "orchestration vignette"

### ISSUE THREAD

**Issue by billdenney** [ropensci/targets#788]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. Convenient helpers for this include [`targets::tar_reprex()`](https://docs.ropensci.org/targets/reference/tar_reprex.html) and  [`reprex::reprex()`](https://reprex.tidyverse.org/reference/reprex.html). A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

In the targets-design vignette section 4.1, there is mention of an "orchestration vignette", but it should point (and link?) to the "orchestration chapter" which is chapter 5 in the same document.  I don't see where the `targets-design` website is created, so sorry if this is not the correct repo for the issue.

**Comment by wlandau** [comment]
Thanks, should be fixed in https://github.com/ropensci-books/targets-design/commit/25a009ebb350a26548d7aeb416839c5b9b1a0ef7.
