### ISSUE TITLE
Add additional arguments to configure S3 bucket access

### ISSUE THREAD

**Issue by linogaliana** [ropensci/targets#798]
## Problem 

Thank you for your excellent package. I tried to run examples from [the doc](https://books.ropensci.org/targets/storage_amazon.html) and struggled with some difficulty in a local minIO instance (S3 compatible).

I am able to connect to my bucket using `paws::s3`:

```r
client <- paws::s3(config = list(
  endpoint = paste0("https://", Sys.getenv("AWS_S3_ENDPOINT"))
  )
)
```

However, when running the example in [targets doc]

```r
# file _targets.R
library(paws)
library(targets)
tar_option_set(
  resources = tar_resources(
    aws = tar_resources_aws(bucket = "<BUCKET_NAME>"))
)

list(
  tar_target(data, rnorm(5), format = "aws_qs")
)
```

where `<BUCKET_NAME>` is my bucket name, I got the following error

```r
> tar_make()
* start target data
x error target data
* end pipeline
Error : _store_ Failed to connect to <BUCKET_NAME>.s3.amazonaws.com port 443: Timed out
Error: callr subprocess failed: _store_ Failed to connect to <BUCKET_NAME>.s3.amazonaws.com port 443: Timed out
```

I saw in `targets` source code, there is no way to add configuration options to mimic the way I would do in my global environment :

https://github.com/ropensci/targets/blob/8b246853b74d9a4ea54c1fbf5c0b00399251f21f/R/utils_aws.R#L81

## Proposal

I guess adding an extra argument to `aws_s3_upload` which is empty by default, e.g.  `config_s3 = list()` (to match default in `paws::s3`) might be sufficient. Then, 

https://github.com/ropensci/targets/blob/8b246853b74d9a4ea54c1fbf5c0b00399251f21f/R/utils_aws.R#L81

would become

```r
client <- paws::s3(config = config_s3)
```

I guess the extra complexity regarding maintenance is limited (feel free to say I am wrong if you think so) but this could solve interesting issues for institutions that host S3 instances. My example was limited to the `endpoint` question but in fact this could give more flexibility regarding credentials (even if they are maybe more appropriately handled by `AWS_*` env variables)

## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**Comment by wlandau** [comment]
Yeah, I think it's time to add a `client` argument to `tar_resources_aws()` to pass custom `paws::s3()` objects. And I believe this would also solve #769.

**Comment by wlandau** [comment]
Could take me a while before I get to this though, unfortunately.

**Comment by linogaliana** [comment]
Thanks for your reply. Would you like me to propose you something in a PR ?

**Comment by wlandau** [comment]
That would be wonderful. I believe the closest similar PRs are #722 and #748.

**Comment by linogaliana** [comment]
Cool I am going to try implementing that

**Comment by wlandau** [comment]
@linogaliana, thanks for exploring this. [Your code](https://github.com/linogaliana/targets/compare/main...config-s3) helped me wrap my head around the problem.

I guess I should have realized this before, but it hit me that the `paws::s3()` object may contain credentials like the access key ID and the secret access key. I doubt all users will need to set those fields, but for the subset who do, I believe `targets` should avoid storing copies of sensitive information. In terms of the design of `targets`, that means we should keep track of the `paws::s3()` object as a `tar_option_set()` option. It is not a perfect solution because users will have to call `tar_option_set(s3 = paws::s3(...))` before `tar_read()` works on S3 objects (whereas I had hoped that `tar_read()` would always just work based on the information in the metadata) but I believe #798 and #769 make it worth doing.

I have a bit more time on my hands now, so I am going to work on this, along with some other cloud-related refactoring. Apologies that https://github.com/linogaliana/targets/compare/main...config-s3 will not be merged. Like I said though, I do appreciate it because it showed me where that direction would lead.

**Comment by wlandau** [comment]
For the sake of staying organized, I am closing this issue in favor of #769. Both will be solved the same way.

**Comment by wlandau** [comment]
As of 6f4484c72af3a56232b1a8b33e3fd685139ffce5, you should be able to supply `tar_option_set(s3_config = list(endpoint = paste0("https://", Sys.getenv("AWS_S3_ENDPOINT")))` in `_targets.R` and access an endpoint reachable with `paws`. @linogaliana, would you give that a try?

**Comment by wlandau** [comment]
Sorry, I am reverting https://github.com/ropensci/targets/commit/6f4484c72af3a56232b1a8b33e3fd685139ffce5 because even that is a security issue. Better to just track the endpoint, which can be done in resources. I will implement this.

**Comment by wlandau** [comment]
Okay, now in 12f5cb8b5be321e74c979c21b464ba7c51d43382, you should be able to set `endpoint` in `tar_resources_aws()`. But be warned: some endpoints are not totally compatible with S3 and may fail to record the version IDs of objects in version-enabled buckets. Google Cloud Storage is like that.

**Comment by linogaliana** [comment]
Wow you've been superfast ! 😍 

I was feeling I was not going in the right direction with my suggestions (since I am not really familiar with the internals of `targets`, I was trying things but did not feel really satisfied). I'm happy if my draft has been of some help. I am going to try your new implementation to see if it solves my problem (I have the feeling it will 😀)

**Comment by linogaliana** [comment]
I confirm, it works like a charm for internal minio cloud storage !
