### ISSUE TITLE
Decouple storage formats from cloud services

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#803]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. Convenient helpers for this include [`targets::tar_reprex()`](https://docs.ropensci.org/targets/reference/tar_reprex.html) and  [`reprex::reprex()`](https://reprex.tidyverse.org/reference/reprex.html). A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

* Deprecate the special "aws_*" storage formats in favor of a new `repository` argument of `tar_target()` which could be `"none"`, `"aws"`, or `"gcp"`.
* Adjust `tar_format()` accordingly.
* Resolve the class structure of `store` objects dynamically instead of implementing all the combinations in advance (e.g. `class_aws_qs`).

This will help scale `targets` to more cloud storage platforms.

**Comment by wlandau** [comment]
cc @MarkEdmondson1234. This change is tightly tied to the rest of the GCS integration, so I think I will have to take that part from here. Sorry about that.

**Comment by MarkEdmondson1234** [comment]
All good! I'm swamped with other stuff at the moment so will wait to see if I can best help at your signal.
