### ISSUE TITLE
"Pruning" dynamic branches that create errors?

### ISSUE THREAD

**Issue by zoews** [ropensci/targets#807]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Hi there! I'm working with @vipham-su on her workflow for data cleaning that uses `targets` to dynamically branch over input files. When a given dynamic branch leads to an issue, we currently use practices like wrapping code into `try()` blocks to safely merge the rows together at a final `bind_rows()` step (we pass along empty `tibbles()` when code fails.) This works OK but leads to some clunky code that is not very readable in some cases.

As far as I can tell, the `error = continue` parameter in `tar_options` does allow a workflow to proceed, but propagates error in a way that will cause a merging step like `bind_rows()` to fail.

Would it be possible to consider some kind of setting for targets that allows a dynamic branch to be "pruned" entirely? That is, if it hits an error, the dynamic branch will not even attempt to run subsequent targets, and the future target that runs `bind_rows()` can safely run without knowledge of the "withered-up" dynamic branch?

Would be happy to work on a PR for this if that's of interest! (Alternatively, apologies if we're misunderstanding something about the erroring/dynamic branch process that already supports this). Thank you!!

**Comment by wlandau** [comment]
Yeah, I think it's time for this feature to exist. As of 2961daef71bfcf73c18b086b6c3aec4b6fbe7331, you can write `tar_target(error = "null")` and errored targets will continue and return a value of `NULL`. Those downstream targets shoudl have an easier time.

**Comment by wlandau** [comment]
Thanks @vipham-su, and I appreciate the testing on your end. PRs welcome if you find ways to improve the docs.
