### ISSUE TITLE
Workflow from `tar_github_actions()` fails if there is no targets-runs branch

### ISSUE THREAD

**Issue by tarensanders** [ropensci/targets#815]
## Prework

* [x ] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [ x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [ x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Using [`targets::tar_reprex()`](https://docs.ropensci.org/targets/reference/tar_reprex.html), [`reprex::reprex()`](https://reprex.tidyverse.org/reference/reprex.html), or similar, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

In trying to use the workflow created by `tar_github_actions()`, I'm running into the following error:

```
Run git config --local user.name "GitHub Actions"
  git config --local user.name "GitHub Actions"
  git config --local user.email "actions@github.com"
  rm -r .gitignore .github/workflows
  git add --all -- ':!renv'
  for file in $(git ls-files -mo --exclude=renv)
  do
    git add $file
  done
  git commit -am "Run pipeline"
  git push origin targets-runs
  shell: sh -e {0}
  env:
    GITHUB_PAT: ***
    RENV_PATHS_ROOT: ~/.local/share/renv
    INCITES_KEY: ***
    LANG: en_US.UTF-[8](https://github.com/tarensanders/cv/runs/5746071805?check_suite_focus=true#step:13:8)
The following paths are ignored by one of your .gitignore files:
_targets/meta/process
Use -f if you really want to add them.
Error: Process completed with exit code 1.
```

In lieu of a reprex, I forked the targets-minimal repo (fork is [here](https://github.com/tarensanders/targets-minimal)). The workflow ran fine the first time. But once I removed the existing targets-runs branch (i.e., to make it the same as a new project), the workflow fails with the same error I am getting. You can see the failed workflow [here](https://github.com/tarensanders/targets-minimal/runs/5746826326?check_suite_focus=true).

I think the issue is that one or more of the files trying to be committed is listed in the `.gitignore` within the `_targets` folder. Changing the line `git add $file` to `git add $file -f` (as suggested by the error message) fixes the issue, but I don't know enough about git to know if that's a reasonable solution.

**EDIT**: Just noting that I don't think `git add $file -f` is the right solution. It commits the meta/process and meta/progress files everytime, which seems excessive. Maybe additional files need to be passed to `exclude`?

**Comment by wlandau** [comment]
Thanks for the FYI. This is probably due to recent changes in the `.gitignore` file in the data store to help [`gittargets`](https://github.com/ropensci/gittargets) work properly. I think a force add is a reasonable solution.
