### ISSUE TITLE
Comparison with Metaflow 

### ISSUE THREAD

**Issue by GitHunter0** [ropensci/targets#822]
Hi folks, first let me say that `targets` is a fantastic project and very much needed in R ecosystem.

I just wanna clear some doubts most people get when starting to use it.

How does `targets` compare to [Metaflow](https://docs.metaflow.org/v/r)?
What are the differences in philosophy and scope?
What `targets` does that `metaflow` does not?
And what `metaflow` does that `targets` does not?

A documentation about that would be awesome.

I believe it will help a lot the beginners trying to find the best tool for the job.

Thank you

**Comment by wlandau** [comment]
https://wlandau.github.io/user-conf-2022/#2 has a summary of the main points, and if that talk gets recorded, I will add it to the `targets` README. Both `targets` and Metaflow are pipeline tools, both support distributed/parallel computing, and both store output data (including cloud storage). `targets` cares more about skipping up-to-date computation to save time, which means it cares more about the current run than past runs (but the slide deck describes data versioning options that work well with `targets`). `targets` is also more tightly integrated with R-specific idioms, from pure functions to R Markdown, giving it a smoother interface experience for most R users. (Metaflow does have R bindings, but it is a python tool underneath, and its interface feels pythonic by comparison.) Metaflow's biggest relative strength is the ability to run on cloud services like AWS Batch, Lambda, and Fargate (and they may have added more by now). `targets` supports traditional schedulers like SLURM, and there are `targets` users who run their pipelines on [AWS ParallelCluster](https://aws.amazon.com/hpc/parallelcluster/). I am working up to AWS Batch etc. for `targets` via [`crew`](https://github.com/wlandau/crew), but that's still a long way off. Metaflow also saves every past run for every user of the project (see the [object hierarchy](https://docs.metaflow.org/metaflow/client)), so it automatically opts in to data versioning, but it can take effort and digging to find what you need. (For the latest run, `tar_read()` and `tar_load()` are easier.)

**Comment by GitHunter0** [comment]
Thank you very much @wlandau , it seems that `targets` is getting pretty complete with the help of its ecosystem, it has a bright future. I will definitively explore `targets` capabilities in my next project, keep the awesome work.
