### ISSUE TITLE
`use_targets()` should assert {rstudioapi} namespace 

### ISSUE THREAD

**Issue by pat-s** [ropensci/targets#836]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `targets` package itself and not a user error, known limitation, or issue from another package that `targets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `targets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/targets/discussions) instead of [issues](https://github.com/ropensci/targets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Using [`targets::tar_reprex()`](https://docs.ropensci.org/targets/reference/tar_reprex.html), [`reprex::reprex()`](https://reprex.tidyverse.org/reference/reprex.html), or similar, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When using `targets::use_targets()` in a fresh {renv} project, {rstudioapi} namespace is not available. 
AFAICS this only suppressed the final file opening of `_targets.R` in the editor but wanted to report it anyhow.

## Reproducible example

```r
> targets::use_targets()
✖ Install packages {{future}}, {{future.callr}}, and {{future.batchtools}} to allow use_targets() to configure tar_make_future() options.
• Writing file "_targets.R".
• Writing file "run.R".
• Writing file "run.sh".
• Modify '_targets.R'
Error in loadNamespace(x) : there is no package called ‘rstudioapi’
```

## Expected result

Functionality is skipped without throwing an error or a warning is issued similar to the ones about the future pkgs.

## Diagnostic information

targets 0.12.0

**Comment by wlandau** [comment]
I agree that the outcome is not desirable for the user, but I would prefer not to have `targets` get involved directly. `use_targets()` is simply calling `usethis::edit_file()`, the latter of which requires `rstudioapi` when invoked inside RStudio. Maybe the default behavior of `usethis::edit_file()` should be to fall back on its current behavior for terminal sessions: to open the user's default text editor. But this is outside the scope of `targets`.
