### ISSUE TITLE
Simplified tar_mermaid à la tar_glimpse

### ISSUE THREAD

**Issue by noamross** [ropensci/targets#848]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

`tar_mermaid()` is excellent for creating sharable DAGs of the targets workflow.  It would be more useful if one could have a bit more control over the output.  For instance, for documentation code in a repo (https://github.com/ecohealthalliance/mpx-diagnosis#readme) I don't want to color the nodes with a legend because the build-state isn't relevant for a code-only repository, and a simpler `tar_glimpse()`-like output would be good.  

I realize that it may just be up to the user to run `tar_network()`, manipulate and build the graph themselves with `DiagrammeR::mermaid()`.  In this case, a small example in the `tar_mermaid()` documentation of how to get something manually near the `tar_mermaid()` output may help get the user (me!) started.

**Comment by wlandau** [comment]
Sounds good to me. 74f618de9774b29978a99a532b161f825fbcf82e implements new arguments `legend` and `color` which you can both set to `FALSE`. And in your case, `outdated = FALSE` will generate the same graph faster.
