### ISSUE TITLE
Handling interleaved R and targets blocks in Rmarkdown

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#881]
### Discussed in https://github.com/ropensci/targets/discussions/880

<div type='discussions-op-text'>

<sup>Originally posted by **Shians** July 18, 2022</sup>
From my understanding the current recommended workflow is to define targets first, in `targets` blocks, then run `tar_make()` before using a bunch of `tar_read()`/`tar_load()` for the rest of the document. I am wondering if there's a way that allows interleaved blocks to work without multiple calls of `tar_make()`. For example

    ```{targets foo, tar_simple = TRUE}
    10
    ```

    ```{r}
    tar_make()
    tar_load("foo")
    print(foo)
    ```

    ```{targets bar, tar_simple = TRUE}
    20
    ```

    ```{r}
    tar_make()
    tar_load("foo")
    print(foo)
    ```

The goal is to be able to run this style of Rmarkdown document without running `tar_make()` at the start of each block.</div>

**Comment by wlandau** [comment]
@Shians, currently this style of document requires the extra code chunks you have described above, but it might be possible to condense it down with new `knitr` engines. I will think about whether this kind of feature is a good fit.

**Comment by Shians** [comment]
There's two version of this that I envision.

1. Two-way interoperability, targets code may use R block objects. So what runs in interactive from top to bottom will run when knit without excessive `tar_make()` calls.
2. One-way interoperability, no targets code depends on R blocks.

2 would be sufficient for me. I don't have a fully clear idea of what is happening right now, but I imagine that the targets are generated as the block are encountered, therefore `tar_make()` can't make the targets further down the script. There might be a way to run something like `tar_parse_rmd()`  followed by `tar_make()` at the start of the document, which will extract out all the targets within the Rmarkdown document, run them, and allow the objects to be accessed by the R blocks.

**Comment by wlandau** [comment]
Internally, there would need to be a call to tar_make() (or e.g. tar_make_clustermq()) for each code chunk, and it would need to run the subset of the pipeline defined up to that point. The proposed feature would make this happen behind the scenes in one code chunk instead two. This way fits with what is already in place, and it doesn’t require preprocessing/scraping all the Rmd’s of a pipeline (which I don’t think could be done well), but there are pitfalls and drawbacks: the overhead of multiple entire tar_make()s, and how this could let users retroactively define upstream targets in downstream code chunks and create self-invalidating pipelines. So I am not sure about this.

**Comment by wlandau** [comment]
After thinking more about this issue, I would rather not go this direction because of the drawbacks I mentioned in https://github.com/ropensci/targets/issues/881#issuecomment-1191195588. To use `targets` as a caching mechanism for `knitr`/Quarto,  https://books.ropensci.org/targets/literate-programming.html#literate-programming-within-a-target is a much more robust approach.
