### ISSUE TITLE
Update parquet version?

### ISSUE THREAD

**Issue by turbanisch** [ropensci/targets#911]
According to the the `tar_target` function documentation, `format = "parquet"` uses version 2.0 which yields the warning `Parquet format version "2.0" is deprecated. Use "2.4" or "2.6" to select format features.` Should the version be updated to the current default within the arrow package, 2.6? Or is there any reason to stick to the previous format?

**Comment by wlandau** [comment]
In development targets, the format is now the default in the arrow package.
