### ISSUE TITLE
Add R shebang to run.R

### ISSUE THREAD

**Issue by petrbouchal** [ropensci/targets#929]
Very minor suggestion, but would be helpful to those of us who set run.R as the custom build script in RStudio:

- would it be possible to have `use_targets()` add an R shebang to the top of run.R? (probably `#!/usr/bin/env Rscript`)
- ideally run.R would also be executable out of the box, but I understand if you don't want targets to handle file permissions.

I am aware of run.sh but prefer to run the pipeline in a standard process when using the RStudio build pane.

**Comment by wlandau** [comment]
Thanks, both done in the most recent commits. `#!/usr/bin/env Rscript` seems harmless because it's just a comment, but I wonder if something else would be needed on Windows.

Related: https://community.rstudio.com/t/recognize-usr-bin-env-rscript-header-as-r-script/59237

**Comment by petrbouchal** [comment]
Hi @wlandau, it seems that `run.R` is no longer executable when created by `tar_targets()` - using {targets} 1.1.3.

I can see it as executable in the package repo and in the installed package directory, but not after it is copied by `use_targets()`.

**Comment by petrbouchal** [comment]
Thanks - happy to run `chmod` myself - I was just wondering if this fell through the cracks in recent updates, but understand it may not be possible to do consistently as part of `use_targets()`.
