### ISSUE TITLE
targets markdown chunks error strangely and fire early when named 'setup'

### ISSUE THREAD

**Issue by KaiAragaki** [ropensci/targets#973]
### Discussed in https://github.com/ropensci/targets/discussions/972

<div type='discussions-op-text'>

<sup>Originally posted by **KaiAragaki** November  4, 2022</sup>
````
```{r}
library(targets)
tar_unscript()
```
````

````
```{targets setup}
tar_target(foo, "bar")
```
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table
Error in if (record) "enable" else "inhibit" : argument is of length zero
````

Things to note:
1. This does not happen with `r` chunks
2. This only happens with chunks named 'setup' - not  'setu' or 'setups'
3. Including a chunk with this name causes it to fire 'early' - even running the first chunk causes the setup chunk to be run.

If this is a privileged chunk name, it may be nice to have a clearer error.

(Beautiful package by the way. Really one of my favorites of all time.)</div>

**Comment by wlandau** [comment]
Thanks, should be fixed in https://github.com/ropensci/targets/commit/32ef529c1c9819c4f1676a67efe28c476e71be6a.
