### ISSUE TITLE
Performance issues with large data.tables

### ISSUE THREAD

**Issue by thejokenott** [ropensci/targets#983]
## Description

For some reason, some functions called as a part of the pipeline take an incredible amount of time when compared to calling them directly.

## Minimal reproducible example

_targets.R
```

library(targets)

get_toy_data <- function() {
  library(data.table)
  dt <- data.table(
    id = sample(1:1e8, 3000)
  )

  dt <- dt[
    ,
    .(date1 = seq.Date(as.Date("2017-01-01"), as.Date("2017-01-31"), by = "day")),
    by = id
  ]

  dt <- dt[
    ,
    .(date2 = seq.Date(as.Date(date1) - 10, as.Date(date1), by = "day")),
    by = .(id, date1)
  ]

  dt[
    ,
    avail := sample(c(rep(FALSE, 9), TRUE), size = nrow(dt), replace = TRUE)
  ]

  return(dt[])
}

f <- function(data) {
  start_time <- Sys.time()
  library(data.table)
  data[avail == TRUE, date2_if_available := date2]
  data[
    ,
    date2_first_available := min(date2_if_available, na.rm = TRUE),
    by = .(id, date1)
  ]
  end_time <- Sys.time()
  print(end_time - start_time)
  return(data[])
}


list(
  tar_target(data, get_toy_data()),
  tar_target(fdata, f(data))
)
```

Now when I run `tar_make(fdata)`, the `fdata` target takes more than 2 minutes to complete. When I run `f(tar_read(data))` instead, it only takes around 2 seconds. There is no issue with the `data` target. I have tried this on both macOS and Ubuntu, both inside and outside of renv, getting similar results everytime. What might be the issue here?

**Comment by wlandau** [comment]
This was a tough one. The slowness came from the large number of warnings from `f()`, which `targets` tried to gather up in a single character string. All those `paste()`s took a long time. 5bc43a7d622b905c7d0c6dc665e9f50e8dc89e59 fixes the issue. Now, the development version of `targets` stops recording warning messages for a target if there have already been 50 warnings or a total of 2048 characters.

**Comment by thejokenott** [comment]
Wow, that was quick! Thank you for the prompt resolution (and for all the work you're putting in this gem).
