### ISSUE TITLE
Implement layouts for tar_visnetwork

### ISSUE THREAD

**Issue by grobins** [ropensci/targets#986]
Hello,

When using tar_visnetwork() to check my pipeline before making I get this graph
<img width="208" alt="image" src="https://user-images.githubusercontent.com/4343493/203219204-132ded64-1792-4f46-a6c4-b97cca729330.png">

Is there a way to make this more condensed as it appears with tar_glimpse()?

**Comment by wlandau** [comment]
You could adjust the targets_only and level_separation arguments of tar_visnetwork().
