### ISSUE TITLE
Improved noticification for tar_destroy() function

### ISSUE THREAD

**Issue by Sage0614** [ropensci/targets#988]
## Proposal

Please describe the new feature. If applicable, write a minimal example in R code or pseudo-code to show input, usage, and desired output.

I feel the tar_destroy() function need a bit more hint beyond print out which folder it will delete , especially the default value is set to "all". I accidentally delete the whole project while I only intended to delete the local data, perhaps listing the top 50 files that are going to be deleted, and not set "all" as the default argument will make these type of accident harder?

**Comment by Sage0614** [comment]
Also, I think the tar_destroy will delete files that are not part of the targets graph as long as you put it under the directory that you set as the store. This is quite unexpected behavior, and worth a warning in the manual that you shouldn't put other files under the store that is being tracked.

**Comment by wlandau** [comment]
I am sorry your data was deleted. In a76a25013ca182c2b3fdb840db7e8ca4bb373cfe, I modified the help file of `tar_destroy()` to make the behavior more apparent.
