### ISSUE TITLE
Set MIME types for AWS file targets by default

### ISSUE THREAD

**Issue by noamross** [ropensci/targets#989]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

It is helpful to be able to inspect targets, especially "file" targets such as images and rendered reports, in the browser. In order to do so AWS must serve the file with an appropriate MIME type.  This is set when the file is uploaded to AWS, the via the `ContentType` field argument in the AWS API.  

I believe the way to do this currently is to set the MIME type in `tar_resources_aws()`, like so:

```
`tar_target(..., format = "file", resources = tar_resources(aws = tar_resources_aws(ContentType="text/html"))`
```

However, since the MIME type is not currently set at all, I do not think there would be much consequence to current workflows of setting it by default, automatically by file name, using `mime::guess_type()`, but it would be much more covenient.  I suggest implementing this in https://github.com/ropensci/targets/blob/main/R/utils_aws.R#L91 .

For R objects, guess_type()` on an `.rds` file returns "application/octet-stream", but "text/plain" on a file with no extensions. I think "application/octet-stream" should be the default for those.

**Comment by wlandau** [comment]
I see the convenience of a default argument for this, but there are so many niche AWS-specific tweaks like this one, and ‘targets’ is not in a position to handle them all well in a principled way. Also, ‘mime’ would need to be a Suggests: package, and ‘targets’ already has several.
